var setContentEditable=_emptyFunction,getEditorDOM=_emptyFunction,getEditorWin=_emptyFunction,formatColorValue=_emptyFunction,getElementUnderCaret=_emptyFunction,getSelectionType=_emptyFunction,getSelectionHTML=_emptyFunction,pasteHTML=_emptyFunction,attachEvent=_emptyFunction,formatContent=_emptyFunction,previewContent=doPreview,sFormatSize=null,sFormatLineHeight=null,bFormatTable=!1,sLineHeader="\u3000\u3000",beforePropertyDialog=null,onRefreshToolbar=null,oTimer=null,_STATUS_CHECK_IDLE_=1E3,sTmpContent=
"",sTmpCssFile="",sTmpBodyProp="";function _emptyFunction(){return null}function execCmd(a,c,b,d){try{null!=getElementUnderCaret()&&(getEditorDOM().execCommand(a,c,b),getEditorWin().focus())}catch(f){null!=d&&alert(d)}}
function fontDialog(a){if("Control"!=getSelectionType()&&isInDesignMode()&&(a||showFrameDialog($wapper.api.getParentPath()+"/font_dialog.htm","\u5b57\u4f53","dialogWidth:250px;dialogHeight:210px",null,"fontDialog(true)")))if(a=getReturnValue().split("\n"),!(""==a[0]&&""==a[1]&&""==a[2]&&""==a[3])){var c=getSelectionHTML();""==c&&(c="\u8bf7\u66ff\u6362");for(var b=getElementUnderCaret(),d="";b;){d=b.color;null!=d&&""!=d&&b.style&&b.style.color&&(d=b.style.color);if(null!=d&&""!=d)break;b=b.parentNode}var f=
'<font style="'+(null!=d&&""!=d?"color:"+d+";":"");""!=a[0]&&(f+="font-family:"+a[0]+";");""!=a[1]&&(f+="font-size:"+a[1]+"px;");""!=a[2]&&(f+="line-height:"+a[2]+"px;");""!=a[3]&&(f+="letter-spacing:"+a[3]+"px;");f+='">';c=c.replace(/<font.[^>]*>/gi,function(){return""});c=c.replace(/<\/font>/gi,function(){return""});c=c.replace(/<div.[^>]*>/gi,function(a){return a+f});c=c.replace(/<\/div>/gi,function(){return"</font></div>"});-1==c.indexOf("<div")&&-1==c.indexOf("<DIV")&&(c=f+c+"</font>");execCmd("RemoveFormat");
pasteHTML(c)}}function setColor(a,c){if(!c){var b=getEditorDOM().queryCommandValue(a);if(!showColor(formatColorValue(b),"setColor('"+a+"',true)"))return}execCmd(a,!1,getReturnValue())}function getElementByTagName(a){for(var c=getElementUnderCaret();c&&c.tagName!=a&&!(c=c.parentNode,null==c||"BODY"==c.tagName););return null!=c&&c.tagName!=a?null:c}
function insertTable(a){if(isInDesignMode()){if(!a){a=null;switch(getSelectionType().toUpperCase()){case "CONTROL":a=getElementUnderCaret();"TABLE"!=a.tagName&&alert("\u8bf7\u9009\u62e9\u8868\u683c\u5bf9\u8c61\uff0c\u518d\u70b9\u51fb\u201c\u63d2\u5165\u8868\u683c\u201d\u6309\u94ae\u65f6\uff0c\u53ef\u4ee5\u6539\u53d8\u8868\u683c\u5c5e\u6027\u3002");return;case "NONE":case "TEXT":if(a=getSelectionHTML(),-1!=a.toUpperCase().indexOf("<TD>")||-1!=a.toUpperCase().indexOf("<TR>")){alert("\u4e0d\u80fd\u5728\u5f53\u524d\u4f4d\u7f6e\u63d2\u5165\u8868\u683c\uff01");
return}}if(!showFrameDialog($wapper.api.getParentPath()+"/insert_table.htm","\u63d2\u5165\u8868\u683c","dialogWidth:450px;dialogHeight:280px",null,"insertTable(true)"))return}pasteHTML(getReturnValue(),"\u5f53\u524d\u4f4d\u7f6e\u4e0d\u80fd\u63d2\u5165\u8868\u683c\uff01")}}
function bodyDialog(){if(isInDesignMode()){var a=getElementByTagName("BODY");a&&(null==beforePropertyDialog||beforePropertyDialog(a))&&showFrameDialog($wapper.api.getParentPath()+"/body_prop.htm?folder="+$wapper.api.getQueryString("folder","")+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web")),"\u8bbe\u7f6e\u9875\u9762\u5c5e\u6027","dialogWidth:500px;dialogHeight:320px")}}
function tableProp(){if(isInDesignMode()){var a=getElementByTagName("TABLE");if(a&&(null==beforePropertyDialog||beforePropertyDialog(a))){var c="table_"+parseInt(65536*Math.random());a.id=c;showFrameDialog($wapper.api.getParentPath()+"/table_prop.htm?folder="+$wapper.api.getQueryString("folder","")+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web"))+"&object_id="+c,"\u8bbe\u7f6e\u8868\u683c\u5c5e\u6027","dialogWidth:500px;dialogHeight:500px")}}}
function cellProp(){if(isInDesignMode()){var a=getElementByTagName("TD");if(a&&(null==beforePropertyDialog||beforePropertyDialog(a))){var c="table_"+parseInt(65536*Math.random());a.id=c;showFrameDialog($wapper.api.getParentPath()+"/cell_prop.htm?folder="+$wapper.api.getQueryString("folder","upload")+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web"))+"&object_id="+c,"\u5355\u5143\u683c\u5c5e\u6027","dialogWidth:480px;dialogHeight:480px;");getEditorWin().focus()}}}
function imageDialog(a,c){if(isInDesignMode()){null==a&&(a="");if(!c){var b=getElementUnderCaret(),d=getSelectionType();if("Control"==d){if("IMG"!=b.tagName){alert("\u65e0\u6cd5\u5728\u9009\u4e2d\u7684\u4f4d\u7f6e\u63d2\u5165\u56fe\u7247\u5bf9\u8c61\uff01");return}if("1"==b.getAttribute("IsMedia")){mediaDialog();return}if(null!=beforePropertyDialog&&!beforePropertyDialog(b))return;b.id="img_"+parseInt(65536*Math.random());a=b.id}else"Text"==d&&execCmd("Unselect");if(!showFrameDialog($wapper.api.getParentPath()+
"/image_dialog.htm?object_id="+a+"&folder="+$wapper.api.getQueryString("folder","upload")+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web",""))+"&img_src_js="+$api.fn.encodeURL($wapper.api.getQueryString("img_src_js","")),sImageDialog,"dialogWidth:600px;dialogHeight:320px;",null,"imageDialog('"+a+"',true)"))return}b=getReturnValue().split("\n");""==a&&pasteHTML(b[0])}}
function mediaDialog(a,c){if(isInDesignMode()){null==a&&(a="");if(!c){var b=getElementUnderCaret(),d=getSelectionType();if("Control"==d){if("IMG"!=b.tagName){alert("\u65e0\u6cd5\u5728\u9009\u4e2d\u7684\u4f4d\u7f6e\u63d2\u5165\u591a\u5a92\u4f53\u5bf9\u8c61\uff01");return}if("1"!=b.getAttribute("IsMedia")){imageDialog();return}if(null!=beforePropertyDialog&&!beforePropertyDialog(b))return;b.id="media_"+parseInt(65536*Math.random());a=b.id}else"Text"==d&&execCmd("Unselect");if(!showFrameDialog($wapper.api.getParentPath()+
"/media_dialog.htm?object_id="+a+"&folder="+$wapper.api.getQueryString("folder","upload")+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web",""))+"&media_src_js="+$api.fn.encodeURL($wapper.api.getQueryString("media_src_js","")),sMediaDialog,"dialogWidth:600px;dialogHeight:320px",null,"mediaDialog('"+a+"',true)"))return}pasteHTML(getReturnValue())}}
function anchorDialog(a,c){if(isInDesignMode()){null==a&&(a="");if(!c){var b=getElementByTagName("A"),d="";switch(getSelectionType()){case "Control":null==b&&(b=getElementUnderCaret());break;case "Text":if(d=getSelectionHTML(),-1!=d.toUpperCase().indexOf("<TD")||-1!=d.toUpperCase().indexOf("<TR")){alert("\u4e0d\u80fd\u5728\u5f53\u524d\u4f4d\u7f6e\u63d2\u5165\u94fe\u63a5\uff01");return}}b&&(a="object_"+parseInt(65536*Math.random()),b.id=a);if(!showFrameDialog($wapper.api.getParentPath()+"/anchor.htm?object_id="+
a+"&folder="+$wapper.api.getQueryString("folder","upload")+"&title="+$api.fn.encodeURL(d)+"&files_web="+$api.fn.encodeURL($wapper.api.getQueryString("files_web",""))+"&anchor_js="+$api.fn.encodeURL($wapper.api.getQueryString("anchor_js",""))+"&attachment="+$wapper.api.getQueryString("attachment",""),"\u8bbe\u7f6e\u8d85\u7ea7\u94fe\u63a5","dialogWidth:480px;dialogHeight:410px",null,"anchorDialog('"+a+"',true)"))return}""==a?pasteHTML(getReturnValue(),"\u5f53\u524d\u4f4d\u7f6e\u4e0d\u80fd\u63d2\u5165\u94fe\u63a5\uff01"):
(b=getEditorDOM().getElementById(a),"A"!=b.tagName&&(d=getEditorDOM().createElement("SPAN"),d.innerHTML=getReturnValue(),b.parentNode.replaceChild(d,b)))}}function specialChar(a){isInDesignMode()&&(a||showFrameDialog($wapper.api.getParentPath()+"/special_char.htm?"+Math.random(),null,"dialogWidth:320px;dialogHeight:290px",null,"specialChar(true)"))&&pasteHTML(getReturnValue())}
function pasteTxtDialog(a){isInDesignMode()&&(a||null!=showFrameDialog($wapper.api.getParentPath()+"/paste_txt.htm","\u7c98\u8d34\u65e0\u683c\u5f0f\u6587\u672c","dialogHeight:340px;dialogWidth:450px",null,"pasteTxtDialog(true)"))&&pasteHTML(getReturnValue())}
function selectedHTMLDialog(a,c){if(isInDesignMode()){null==a&&(a="");if(!c){var b=null;switch(getSelectionType().toUpperCase()){case "CONTROL":b=getElementUnderCaret();break;case "NONE":b=getElementByTagName("TD");null==b&&(b=getElementByTagName("TABLE"));break;case "TEXT":if(sHtml=getSelectionHTML(),-1!=sHtml.toUpperCase().indexOf("<TD")||-1!=sHtml.toUpperCase().indexOf("<TR"))b=getElementByTagName("TABLE")}null!=b&&(a="object_"+parseInt(65536*Math.random()),b.id=a);if(null==showFrameDialog($wapper.api.getParentPath()+
"/selected_html.htm?object_id="+a,"\u7f16\u8f91HTML","dialogHeight:340px;dialogWidth:450px",null,"selectedHTMLDialog('"+a+"',true)"))return}if(""!=a)if(b=getEditorDOM().getElementById(a),"TD"==b.tagName)b.innerHTML=getReturnValue();else{var d=getEditorDOM().createElement("SPAN");d.innerHTML=getReturnValue();b.parentNode.replaceChild(d,b)}else pasteHTML(getReturnValue())}}
function killWord(a){var c=!1;null==a&&(c=!0,a=getEditorDOM().body.innerHTML);a=a.replace(/<(\w[^>]*) class=([^ |>]*)([^>]*)/gi,"<$1$3");a=a.replace(/<(\w[^>]*) style="([^"]*)"([^>]*)/gi,"<$1$3");a=a.replace(/mso\-([^;|"]*)/gi,"");a=a.replace(/font\-([^;|"]*)/gi,"");a=a.replace(/<(\w[^>]*) lang=([^ |>]*)([^>]*)/gi,"<$1$3");a=a.replace(/<\\?\?xml[^>]*>/gi,"");a=a.replace(/<(v:imagedata[^>]*) src=([^ |>]*)([^>]*)/gi,"<img src=$2");a=a.replace(/<\/?\w+:[^>]*>/gi,"");a=a.replace(/<\/?span[^>]*>/gi,"");
a=a.replace(/<\/?strong[^>]*>/gi,"");a=a.replace(/<\/?font[^>]*>/gi,"");a=a.replace(/<!-[^>]*>/gi,"");a=a.replace(/<meta(\n|.)*?>/ig,"");a=a.replace(/<!(\n|.)*?>/ig,"");a=a.replace(/<style[^>]*>(\n|.)*?<\/style>/ig,"");a=a.replace(/<script[^>]*>(\n|.)*?<\/script>/ig,"");a=a.replace(/<w:[^>]+>(\n|.)*?<\/w:[^>]+>/ig,"");a=a.replace(/<xml>(\n|.)*?<\/xml>/ig,"");a=a.replace(/\r\n|\n|\r/ig,"");if(c)getEditorDOM().body.innerHTML=a;else return a}
function propertyDialog(){var a=getElementUnderCaret();if(null!=a){switch(a.tagName){case "TABLE":tableProp();break;case "IMG":imageDialog();break;case "EMBED":mediaDialog();break;case "MARQUEE":break;default:bodyDialog()}getEditorWin().focus()}}function isInDesignMode(){return"none"==document.getElementById("txtSource").style.display.toLowerCase()}function _dealWithMedia(){}
function getContent(){""==document.getElementById("txtSource").style.display&&(getEditorDOM().body.innerHTML=txtSource.value);_dealWithMedia();return formatContent(getEditorDOM().body.innerHTML)}function getText(){return $api.fn.getTextFromHTML(getContent())}function setContent(a,c,b){$api.fn._IE()||0==a.toLowerCase().indexOf("<p>")&&a.toLowerCase().indexOf("</p>")==a.length-4&&(a="<div>"+a.substring(3,a.length-4)+"</div>");sTmpContent=a;sTmpCssFile=b;sTmpBodyProp=c;_setContent(0)}
function _setContent(a){try{getEditorDOM().body.innerHTML=sTmpContent.replace(/>\r\n/g,">");if(null!=sTmpCssFile&&""!=sTmpCssFile){var c=getEditorDOM().createElement("LINK");c.rel="stylesheet";c.href=sTmpCssFile;getEditorDOM().getElementsByTagName("HEAD")[0].appendChild(c)}null!=sTmpBodyProp&&""!=sTmpBodyProp&&setBodyProps(sTmpBodyProp)}catch(b){a++,50==a?alert("\u5185\u5bb9\u52a0\u8f7d\u5931\u8d25"):window.setTimeout("_setContent("+a+")",20)}}
function setBodyProps(a){try{for(var c=a.split(" "),a=0;a<c.length;a++)if(-1!=c[a].replace(/ /g,"").replace(/\"/g,"").indexOf("=")){var b=c[a].split("=");if(null!=b&&2==b.length&&""!=b[0].replace(/ /g,"").replace(/\"/g,"")&&""!=b[1].replace(/ /g,"").replace(/\"/g,""))if("bgcolor"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase())getEditorDOM().body.bgColor=b[1].replace(/ /g,"").replace(/\"/g,"");else if("style"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase())for(var d=b[1].replace(/ /g,
"").replace(/\"/g,"").split(";"),f=0;f<d.length;f++)-1!=d[f].replace(/ /g,"").replace(/\"/g,"").indexOf(":")&&(b=d[f].split(":"),null!=b&&2==b.length&&""!=b[0].replace(/ /g,"").replace(/\"/g,"")&&""!=b[1].replace(/ /g,"").replace(/\"/g,"")&&("margin"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase()?getEditorDOM().body.style.margin=b[1].replace(/ /g,"").replace(/\"/g,""):"background"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase()?getEditorDOM().body.style.background=b[1].replace(/ /g,
"").replace(/\"/g,""):"background-repeat"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase()?getEditorDOM().body.style.backgroundRepeat=b[1].replace(/ /g,"").replace(/\"/g,""):"background-position"==b[0].replace(/ /g,"").replace(/\"/g,"").toLowerCase()&&(getEditorDOM().body.style.backgroundPosition=b[1].replace(/ /g,"").replace(/\"/g,""))))}}catch(g){alert("\u52a0\u8f7dBODY\u5c5e\u6027\u5931\u8d25")}}
function _dealWithMedia(){for(var a=getEditorDOM().getElementsByTagName("SCRIPT"),c=0;c<a.length;c++)"1"==a[c].getAttribute("IsMediaScript","0")&&($api.fn._IE()?a[c].removeNode(!0):a[c].removeChild(!0),c--);a=getEditorDOM().getElementsByTagName("IMG");for(c=0;c<a.length;c++)if("1"==a[c].getAttribute("IsMedia","0")){var b=getDisplayHtmlOfMedia(a[c].getAttribute("MediaSrc"),"1"==a[c].getAttribute("AutoStartMedia"),"1"==a[c].getAttribute("LoopPlay"),"1"==a[c].getAttribute("ShowPlayControl"),a[c].offsetWidth,
a[c].offsetHeight),b=b.replace(/\\/g,"\\\\"),b=b.replace(/\n/g,"\\n"),b=b.replace(/\"/g,'\\"'),d=getEditorDOM().createElement("SPAN");d.innerHTML=$api.fn.getOuterHTML(a[c])+'<script language=javascript IsMediaScript=1>document.write("'+b+'");<\/script>';a[c].parentNode.replaceChild(d,a[c])}}
function getBodyProps(){var a=getEditorDOM().body;if(null!=a){var c="",b="",c="margin:"+(""==a.style.margin?"0":parseInt(a.style.margin))+";",d="",d=a.bgColor;if(""==d||null==d||"none"==d)d=a.style.backgroundColor;""!=d&&(b+=" bgcolor="+d+" ");try{null!=a.getAttribute("background")&&(c+="background:"+a.background+";");var f=a.style.backgroundRepeat;f||(f="repeat");var c=c+("background-repeat:"+f+";"),g=a.style.backgroundPosition;if(""!=g){var e=trim(g).split(" ");if(2!=e.length)return;c+="background-position:"+
("center"==e[0]?"50%":"top"==e[0]?"0":"bottom"==e[0]?"100%":-1==e[0].indexOf("%")?parseInt(e[0]):e[0]);c+=" "+("center"==e[1]?"50%":"left"==e[1]?"0":"right"==e[1]?"100%":-1==e[1].indexOf("%")?parseInt(e[1]):e[1])}}catch(h){}return b+' style="'+c+'"'}}
function doPreview(){try{if($api.fn._IE()){var a=window.open("","w_preview");a.focus();a.document.open();a.document.write("<HTML><HEAD></HEAD><BODY "+getBodyProps()+">"+getContent().replace(/>\r\n/g,">")+"</BODY></HTML>");a.document.title="\u5feb\u901f\u9884\u89c8";a.document.close()}else alert("\u6682\u4e0d\u652f\u6301\u8be5\u529f\u80fd\uff01\u8bf7\u4f7f\u7528IE\u5185\u6838\u6d4f\u89c8\u5668\uff01")}catch(c){}}function clearHtml(){}
function autoFormat(){var a="",c=null;switch(getSelectionType().toUpperCase()){case "CONTROL":c=getElementUnderCaret();break;case "NONE":c=getElementByTagName("TD");null==c&&(c=getElementByTagName("TABLE"));break;case "TEXT":a=getSelectionHTML()}null!=c&&(a="TD"==c.tagName?c.innerHTML:$api.fn.getOuterHTML(c));var b=!1;if(null==c&&(""==a||null==a))b=!0,a=getEditorDOM().body.innerHTML;a=killWord(a);b?getEditorDOM().body.innerHTML=formatText(a):null==c?pasteHTML(formatText(a)):"TD"==c.tagName?c.innerHTML=
formatText(a,!0):pasteHTML(formatText(a));if(bFormatTable&&b&&(a=getEditorDOM().getElementsByTagName("TABLE"),null!=a))if(null!=a.length)for(c=0;c<a.length;c++)formatTable(a[c]);else formatTable(a)}
function formatTable(a){if(!(null==a||"TABLE"!=a.tagName)){var c="",c=0==a.cellSpacing?a.borderColor:a.style.backgroundColor;""==c&&(c="black");a.style.borderLeft="solid "+c+" 1px";a.style.borderTop="solid "+c+" 1px";for(var b=0;b<a.rows.length;b++)for(var d=0;d<a.rows[b].cells.length;d++)a.rows[b].cells[d].style.borderRight="solid "+c+" 1px",a.rows[b].cells[d].style.borderBottom="solid "+c+" 1px",a.rows[b].cells[d].style.padding="2px",a.rows[b].cells[d].innerHTML=""==a.rows[b].cells[d].innerHTML.replace(/ /gi,
"")?"&nbsp;":formatText(a.rows[b].cells[d].innerHTML,!0);a.cellSpacing=0}}
function formatText(a,c){var a=a.replace(/<p.*?>/gi,""),a=a.replace(/<\/p>/gi,"<br>"),a=a.replace(/<span.*?>/gi,"<font>"),a=a.replace(/<\/span>/gi,"</font>"),a=a.replace(/<div.*?>/gi,""),a=a.replace(/<\/div>/gi,"<br>"),a=a.replace(/\u3000\u3000/gi,"<br>"),a=a.replace(/<\!----\>/gi,""),b=a.split("<br>");if(0<=b.length){a="";for(loop=0;loop<b.length;loop++)a=a+"<p>"+b[loop]}b=a.split("<BR>");if(0<=b.length){a="";for(loop=0;loop<b.length;loop++)a=a+"<p>"+b[loop]}b=a.split("<P>");if(0<=b.length){a="";
for(loop=0;loop<b.length;loop++)a=a+"<p>"+b[loop]}b=a.split("</P>");if(0<=b.length){a="";for(loop=0;loop<b.length;loop++)a=a+"<p>"+b[loop]}b=a.split("</p>");if(0<=b.length){a="";for(loop=0;loop<b.length;loop++)a=a+"<p>"+b[loop]}b=a.split("<p>");if(0<=b.length){a="";for(loop=0;loop<b.length;loop++)a+=mytrim(b[loop],""==a&&30>b[loop].length&&(b[loop].indexOf(":")>=b[loop].length-3||b[loop].indexOf("\uff1a")>=b[loop].length-3)||c&&30>b[loop].length)}a=a.replace(/<p>\u3000\u3000<t/gi,"<t");a=a.replace(/<p>\u3000\u3000<\/t/gi,
"</t");a=a.replace(/<p><\/p>/gi,"");a=a.replace(/<p>/gi,'<div style="line-height:'+(null==sFormatLineHeight?"20px":sFormatLineHeight)+";font-size:"+(null==sFormatSize?"10pt":sFormatSize)+'">');return a=a.replace(/<\/p>/gi,"</div>")}
function mytrim(a,c){for(var a=a.replace(/&nbsp;/gi,"\u3000"),b=a.length,d="",f=0,g=0;g<b;g++){var e=a.charAt(g);0==f?"\r"!=e&&"\n"!=e&&" "!=e&&"\u3000"!=e&&"\t"!=e&&(d+=e,f=1):d+=e}a=d;b=a.length;f=0;d="";for(g=b-1;0<=g;g--)e=a.charAt(g),0==f?"\r"!=e&&"\n"!=e&&" "!=e&&"\u3000"!=e&&"\t"!=e&&(d=e+d,f=1):d=e+d;a.replace(/\u3000/gi,"&nbsp;");return""!=d?"<p>"+(c?"":sLineHeader)+d+"</p>":""};
