var nButtons1=parseInt($wapper.api.getQueryString("button1","2047")),nButtons2=parseInt($wapper.api.getQueryString("button2","2047")),nTextButton1=parseInt($wapper.api.getQueryString("text_button1",0)),nTextButton2=parseInt($wapper.api.getQueryString("text_button2",0)),bToolbar2="1"==$wapper.api.getQueryString("toolbar2","1"),toolbar1=new Toolbar,toolbar2=bToolbar2?new Toolbar:toolbar1,toolbar3=new Toolbar,sRefreshFunc=$wapper.api.getQueryString("refresh_func","");
function hasProperty(a,b){return(a&b)==b}var bAddSeparator=!1;if("undefined"==typeof sTlbTableProp)var sTlbTableProp="\u8868\u683c\u5c5e\u6027";if("undefined"==typeof sTlbRemoveWordFormat)var sTlbRemoveWordFormat="\u79fb\u9664Word\u683c\u5f0f";if("undefined"==typeof sTlbPasteNoFormat)var sTlbPasteNoFormat="\u7c98\u8d34\u65e0\u683c\u5f0f\u6587\u672c";if("undefined"==typeof sTlbAutoFormat)var sTlbAutoFormat="\u81ea\u52a8\u6392\u7248";if("undefined"==typeof sTrikeThrough)var sTrikeThrough="\u5220\u9664\u7ebf";
toolbar1.addHeader();hasProperty(nButtons1,1)&&(toolbar1.addButton(new ToolbarButton("cut","",sTlbCut,"execCmd('Cut')")),toolbar1.addButton(new ToolbarButton("copy","",sTlbCopy,"execCmd('Copy')")),toolbar1.addButton(new ToolbarButton("paste","",sTlbPaste,"execCmd('Paste')")),bAddSeparator=!0);
hasProperty(nButtons1,2)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("undo","",sTlbUndo,"execCmd('Undo')")),toolbar1.addButton(new ToolbarButton("redo","",sTlbRedo,"execCmd('Redo')")),bAddSeparator=!0);
hasProperty(nButtons1,4)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("bold","",sTlbBold,"execCmd('Bold')",toolbar1.tlbCheckBox)),toolbar1.addButton(new ToolbarButton("italic","",sTlbItalic,"execCmd('Italic')",toolbar1.tlbCheckBox)),toolbar1.addButton(new ToolbarButton("underline","",sTlbUnderline,"execCmd('Underline')",toolbar1.tlbCheckBox)),toolbar1.addButton(new ToolbarButton("s","",sTrikeThrough,"execCmd('StrikeThrough')",toolbar1.tlbCheckBox)),bAddSeparator=!0);
hasProperty(nButtons1,8)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("font","",sTlbFont,"fontDialog()")),bAddSeparator=!0);hasProperty(nButtons1,16)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("fgcolor","",sTlbFgcolor,"setColor('ForeColor')")),toolbar1.addButton(new ToolbarButton("bgcolor","",sTlbBgcolor,"setColor('BackColor')")),bAddSeparator=!0);
hasProperty(nButtons1,32)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("left","",sTlbLeft,"execCmd('JustifyLeft')",toolbar1.tlbRadio)),toolbar1.addButton(new ToolbarButton("center","",sTlbCenter,"execCmd('JustifyCenter')",toolbar1.tlbRadio)),toolbar1.addButton(new ToolbarButton("right","",sTlbRight,"execCmd('JustifyRight')",toolbar1.tlbRadio)),bAddSeparator=!0);
(hasProperty(nButtons1,64)||hasProperty(nButtons1,128)||hasProperty(nButtons1,256))&&toolbar1.addArrow("","1"==$wapper.api.getQueryString("arrow1","0"));
hasProperty(nButtons1,64)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("numlist","",sTlbNumlist,"execCmd('InsertOrderedList')",toolbar1.tlbRadio)),toolbar1.addButton(new ToolbarButton("bullist","",sTlbBullist,"execCmd('InsertUnorderedList')",toolbar1.tlbRadio)),toolbar1.addButton(new ToolbarButton("outdent","",sTlbOutdent,"execCmd('Outdent')")),toolbar1.addButton(new ToolbarButton("indent","",sTlbIndent,"execCmd('Indent')")),bAddSeparator=!0);
hasProperty(nButtons1,128)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("sup","",sTlbSup,"execCmd('Superscript')",toolbar1.tlbCheckBox)),toolbar1.addButton(new ToolbarButton("sub","",sTlbSub,"execCmd('Subscript')",toolbar1.tlbCheckBox)),bAddSeparator=!0);
hasProperty(nButtons1,256)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("removefmt","",sTlbRemovefmt,"execCmd('RemoveFormat')")),toolbar1.addButton(new ToolbarButton("removelink","",sTlbRemoveAnchor,"execCmd('Unlink')")),bAddSeparator=!0);(hasProperty(nButtons1,64)||hasProperty(nButtons1,128)||hasProperty(nButtons1,256))&&toolbar1.addArrow();
hasProperty(nButtons1,256)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("remove_word_format","",sTlbRemoveWordFormat,"killWord()")),toolbar1.addButton(new ToolbarButton("paste_no_format","",sTlbPasteNoFormat,"pasteTxtDialog()")));hasProperty(nButtons1,512)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("autoformat","",sTlbAutoFormat,"autoFormat()")),bAddSeparator=!0);
hasProperty(nButtons1,1024)&&(bAddSeparator&&toolbar1.addSeparator(),toolbar1.addButton(new ToolbarButton("prop",1024==(nTextButton1&1024)?sTlbProp:"",sTlbProp,"propertyDialog()")),bAddSeparator=!0);toolbar2.addHeader();
hasProperty(nButtons2,1)&&(toolbar2.addButton(new ToolbarButton("insttbl","",sTlbTable,"insertTable()")),toolbar2.addArrow(sTlbExpandTable,"1"==$wapper.api.getQueryString("arrow1","0")),toolbar2.addButton(new ToolbarButton("instrow","",sTlbInstRow,"insertRow()")),toolbar2.addButton(new ToolbarButton("deleterow","",sTlbDelRow,"deleteRow()")),toolbar2.addButton(new ToolbarButton("instcol","",sTlbInstCol,"insertCol()")),toolbar2.addButton(new ToolbarButton("deletecol","",sTlbDelCol,"deleteCol()")),toolbar2.addButton(new ToolbarButton("instcell",
"",sTlbInstCell,"insertCell()")),toolbar2.addButton(new ToolbarButton("deletecell","",sTlbDelCell,"deleteCell()")),toolbar2.addButton(new ToolbarButton("mrgcell","",sTlbMergeCell,"mergeCell()")),toolbar2.addButton(new ToolbarButton("spltcell","",sTlbSplitCell,"splitCell()")),toolbar2.addButton(new ToolbarButton("cellprop","",sTlbCellProp,"cellProp()")),toolbar2.addButton(new ToolbarButton("tableprop","",sTlbTableProp,"tableProp()")),toolbar2.addArrow(sTlbColspandTable),bAddSeparator=!0);
hasProperty(nButtons2,2)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("specchar",2==(nTextButton2&2)?sTlbChar:"",sTlbChar,"specialChar()")),bAddSeparator=!1);hasProperty(nButtons2,512)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("hr",4==(nTextButton2&4)?"undefined"==typeof sTlbHr?"\u6c34\u5e73\u7ebf":sTlbHr:"","undefined"==typeof sTlbHr?"\u6c34\u5e73\u7ebf":sTlbHr,"pasteHTML('<hr/>')")),bAddSeparator=!1);
hasProperty(nButtons2,4)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("anchor",4==(nTextButton2&4)?sTlbAnchor:"",sTlbAnchor,"anchorDialog()")),bAddSeparator=!1);hasProperty(nButtons2,8)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("instimg",8==(nTextButton2&8)?sTlbPic:"",sTlbPic,"imageDialog()")),bAddSeparator=!1);
hasProperty(nButtons2,16)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("media",16==(nTextButton2&16)?sTlbMedia:"",sTlbMedia,"mediaDialog()")),bAddSeparator=!1);hasProperty(nButtons2,32)&&(toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("htmledit",32==(nTextButton2&32)?sTlbHtml:"",sTlbHtml,"selectedHTMLDialog()")));bAddSeparator=!0;
hasProperty(nButtons2,64)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("edit",64==(nTextButton2&64)?sTlbEdit:"",sTlbEdit,"toDesignMode()",toolbar1.tlbRadio)),bAddSeparator=!1);hasProperty(nButtons2,128)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("script",128==(nTextButton2&128)?sTlbSource:"",sTlbSource,"toSourceMode()",toolbar1.tlbRadio)),bAddSeparator=!1);
hasProperty(nButtons2,256)&&(bAddSeparator&&toolbar2.addSeparator(),toolbar2.addButton(new ToolbarButton("preview",256==(nTextButton2&256)?sTlbPrev:"",sTlbPrev,"previewContent()")),bAddSeparator=!1);function getSelfToolbar(){return toolbar3}function addToolbarButton(a,b,c,d,e){toolbar3.addButton(new ToolbarButton(a,b,c,d,e))}function addToolbarSeparator(){toolbar3.addSeparator()}function refreshSelfToolbar(){document.getElementById("tdSelfToolbar").innerHTML=toolbar3.getHTML()}
function refreshSystemToolbar(){null!=oTimer&&window.clearTimeout(oTimer);if(isInDesignMode()){try{if(toolbar1.getButton(sTlbCopy)&&(toolbar1.getButton(sTlbCopy).setEnabled(getEditorDOM().queryCommandEnabled("Copy")),toolbar1.getButton(sTlbCut).setEnabled(getEditorDOM().queryCommandEnabled("Cut")),toolbar1.getButton(sTlbPaste).setEnabled(getEditorDOM().queryCommandEnabled("Paste"))),toolbar1.getButton(sTlbBold)&&(toolbar1.getButton(sTlbBold).setState(getEditorDOM().queryCommandState("Bold")?toolbar1.tlbPressed:
toolbar1.tlbUnpressed),toolbar1.getButton(sTlbItalic).setState(getEditorDOM().queryCommandState("Italic")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),toolbar1.getButton(sTlbUnderline).setState(getEditorDOM().queryCommandState("Underline")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),toolbar1.getButton(sTlbBold).setEnabled(getEditorDOM().queryCommandEnabled("Bold")),toolbar1.getButton(sTlbItalic).setEnabled(getEditorDOM().queryCommandEnabled("Italic")),toolbar1.getButton(sTlbUnderline).setEnabled(getEditorDOM().queryCommandEnabled("Underline"))),
toolbar1.getButton(sTlbUndo)&&(toolbar1.getButton(sTlbUndo).setEnabled(getEditorDOM().queryCommandEnabled("Undo")),toolbar1.getButton(sTlbRedo).setEnabled(getEditorDOM().queryCommandEnabled("Redo"))),toolbar1.getButton(sTlbLeft)&&(toolbar1.getButton(sTlbLeft).setState(getEditorDOM().queryCommandState("JustifyLeft")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),toolbar1.getButton(sTlbCenter).setState(getEditorDOM().queryCommandState("JustifyCenter")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),toolbar1.getButton(sTlbRight).setState(getEditorDOM().queryCommandState("JustifyRight")?
toolbar1.tlbPressed:toolbar1.tlbUnpressed)),toolbar1.getButton(sTlbNumlist)&&(toolbar1.getButton(sTlbNumlist).setState(getEditorDOM().queryCommandState("InsertOrderedList")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),toolbar1.getButton(sTlbBullist).setState(getEditorDOM().queryCommandState("InsertUnorderedList")?toolbar1.tlbPressed:toolbar1.tlbUnpressed)),toolbar1.getButton(sTlbSup)&&(toolbar1.getButton(sTlbSup).setState(getEditorDOM().queryCommandState("Superscript")?toolbar1.tlbPressed:toolbar1.tlbUnpressed),
toolbar1.getButton(sTlbSub).setState(getEditorDOM().queryCommandState("Subscript")?toolbar1.tlbPressed:toolbar1.tlbUnpressed)),toolbar2.getButton(sTlbInstRow)){var a=getElementByTagName("TABLE");toolbar2.getButton(sTlbInstRow).setEnabled(null!=a);toolbar2.getButton(sTlbDelRow).setEnabled(null!=a);toolbar2.getButton(sTlbInstCol).setEnabled(null!=a);toolbar2.getButton(sTlbDelCol).setEnabled(null!=a);toolbar2.getButton(sTlbInstCell).setEnabled(null!=a);toolbar2.getButton(sTlbDelCell).setEnabled(null!=
a);toolbar2.getButton(sTlbMergeCell).setEnabled(null!=a);toolbar2.getButton(sTlbSplitCell).setEnabled(null!=a);toolbar2.getButton(sTlbCellProp).setEnabled(null!=a);toolbar2.getButton(sTlbTableProp).setEnabled(null!=a)}}catch(b){}a=$wapper.api.getQueryString("refresh_func","");""!=a&&eval("try{"+a+"}catch(e){}");if(null!=onRefreshToolbar)try{onRefreshToolbar()}catch(c){}}oTimer=window.setTimeout("refreshSystemToolbar()",_STATUS_CHECK_IDLE_)}
function toSourceMode(){"none"==txtSource.style.display&&(document.getElementById("DHTMLEditor").style.height=0,txtSource.style.display="",txtSource.value=getEditorDOM().body.innerHTML,_resetAllToolButtons(!1))}function toDesignMode(){if("none"!=txtSource.style.display){document.getElementById("DHTMLEditor").style.height="100%";txtSource.style.display="none";try{getEditorDOM().body.innerHTML=txtSource.value,_resetAllToolButtons(!0)}catch(a){}}}
function _resetAllToolButtons(a){for(var b=0;b<toolbar1.buttons.length;b++){var c=toolbar1.getButton(toolbar1.buttons[b].tiptext);c&&c.setEnabled(a)}for(b=0;b<toolbar2.buttons.length;b++)toolbar2.buttons[b].tiptext==sTlbEdit||toolbar2.buttons[b].tiptext==sTlbSource||toolbar2.buttons[b].tiptext==sTlbPrev||(c=toolbar2.getButton(toolbar2.buttons[b].tiptext))&&c.setEnabled(a)}function editor_oncontextmenu(){return!1};
