function WebForm(c){this.win_dom=c;this.formName="form1";this.sHiddenFrameName="w_hidden";this.sFrmName=this.searchBinding=this.requiredCtrls=this.formAction="";this._wf_insert_done=0;this.setFormName=_wf_setFormName;this.setAction=_wf_setFormAction;this.getAction=_wf_getFormAction;this.doOK=_wf_doOK;this.beforeSetFocus=this.isFormValidate=null;this.submit=_wf_submit;this.ajax_form="";this.load=_wf_ajaxLoad;this.unload=_wf_ajaxUnload;this.sConflictCtrlList="";this.addConflictCtrl=_wf_conflict;this.afterAjaxLoad=
function(){};this.resetFormAction=null;this.afterAction=_wf_afterAction;this.afterEdit=this.afterInsert=null;this.getReturnValue=_wf_getReturnValue;this.getIdValue=_wf_getIdValue;this.doReturn=_wf_doReturn;this.setSearchBinding=_wf_setSearchBinding;this.getReturnURL=null;this.getDefaultReturnURL=_wf_getDefaultReturnURL;this.setRequired=_wf_setRequired;this.autoCheckFrom=_wf_autoCheckFrom;this.getHiddenFrame=_wf_getHiddenFrame;this.dealWithDHEditor=_wf_dealWithDHEditor;this.sDHEditorList="\n";this.dealWithDateControl2=
_wf_dealWithDateControl2;this._web_form_index=null;this.win_dom.win.returnValue=""}
function _wf_ajaxLoad(c){if(0<this.sConflictCtrlList.length)for(var a=this.sConflictCtrlList.split(","),b=0;b<a.length;b++)this.win_dom.win.document.getElementById(a[b])&&(this.win_dom.win.document.getElementById(a[b]).style.display="none");this.win_dom.win.document.getElementById($api.fn._form_prefix+this.ajax_form).style.display="";a=parseInt(this.win_dom.win.document.getElementById($api.fn._form_prefix+this.ajax_form).offsetTop);a=parseInt(this.win_dom.win.document.body.clientHeight)-a-60;parseInt(this.win_dom.win.document.getElementById($api.fn._form_prefix+
this.ajax_form).offsetLeft);40>a&&(a=40);a='<div id="'+$api.fn._form_prefix+this.ajax_form+'_loading" style="display:none;position:absolute;background:url('+$api._libaray_path+"/images/blue_bg.png);z-index:9999;height:"+a+";width:100%;text-align:center;padding-top:"+a/3+'px"><img src='+$api._libaray_path+"/images/loading.gif></div>";this.win_dom.win.document.getElementById($api.fn._form_prefix+this.ajax_form).innerHTML+=a;c=$api.fn.getAbsolutePath(this.win_dom,c);$api.fn.getAjaxData(this.win_dom,
$api.fn.getAjaxObjById(this.win_dom,$api.fn._form_prefix+this.ajax_form),c,"$wapper.fn."+("form1"==this.formName?"webForm":"webForm_"+this.formName)+".afterAjaxLoad()")}function _wf_ajaxUnload(){if(0<this.sConflictCtrlList.length)for(var c=this.sConflictCtrlList.split(","),a=0;a<c.length;a++)this.win_dom.win.document.getElementById(c[a])&&(this.win_dom.win.document.getElementById(c[a]).style.display="")}function _wf_conflict(c){this.sConflictCtrlList+=(""==this.sConflictCtrlList?"":",")+c}
function _wf_setFormName(c){this.formName=c}function _wf_setFormAction(c){this.formAction=c}function _wf_getFormAction(){return this.formAction}function _wf_setSearchBinding(c,a){this.searchBinding+=(""==this.searchBinding?"":",")+c+","+a}
function _wf_submit(){for(var c=this.win_dom.win.document.getElementById(this.formName),a="-1"==c._txtIdValues.value||""==c._txtIdValues.value,a=a&&-1==_wf_ed(this,c._txtIdFields.value).indexOf(","),b=_wf_ed(this,c._txtIdFields.value).split(","),e=$api._gap_+"/servlet/com.lemon.web.ActionServlet?handler="+$api.fn.encodeURL(this.formAction)+"&op="+(a?"new_":"edit_")+_wf_ed(this,c._txtTableName.value),d=0;d<b.length;d++){var f=$api.fn.getQueryString(this.win_dom,b[d]);if(null==f||""==f)f=c._txtIdValues.value;
e+="&"+b[d]+"="+$api.fn.encodeURL(f)}e+="&web_form_action=1&script="+$api.fn.encodeURL("parent."+("form1"==this.formName?"webForm":"webForm_"+this.formName)+".afterAction('"+(a?"new":"edit")+"');")+"&"+Math.random();if(null!=this.resetFormAction&&(e=this.resetFormAction(e),!e))return;c.action=e;b=_wf_ed(this,c._txtIndexFields.value).split(",");e="";for(d=0;d<b.length&&0==b.length%4;d+=4)e+=(""==e?"":",")+b[d]+","+b[d+1]+","+b[d+2]+",",""==b[d+3].replace(/ /g,"")?(f=_wf_getInputRemark(c.elements.namedItem(b[d+
2])).replace(/\uff1a/g,""),e+=f):e+=b[d+3];c._txtIndexFields.value=_wf_ed(this,e);this.dealWithDateControl2("beforesubmit");c.submit();this.dealWithDateControl2("aftersubmit");a&&(this._wf_insert_done=1)}function _wf_doOK(){this.dealWithDHEditor("submit");this.autoCheckFrom()&&(null==this.isFormValidate||this.isFormValidate())&&this.submit()}
function _wf_afterAction(c){this.win_dom.win.document.getElementById(this.formName)._txtIdValues.value=this.win_dom.win.returnValue;if("new"==c)if(null==this.afterInsert){if(null!=this.afterEdit){this.afterEdit();return}}else{this.afterInsert();return}else if(null!=this.afterEdit){this.afterEdit();return}alert($api.lang.form._wf_after_action)}function _wf_getReturnValue(){return this.win_dom.win.returnValue}
function _wf_getIdValue(){return this.win_dom.win.document.getElementById(this.formName)._txtIdValues.value}
function _wf_getDefaultReturnURL(){var c=$api.fn.getQueryString(this.win_dom,"returl",$api._gap_);-1==c.toLowerCase().indexOf("http://")&&"/"!=c.substring(0,1)&&(c=$api.fn.getParentPath(this.win_dom)+"/"+c);if(""!=this.searchBinding&&1==this._wf_insert_done)for(var a=this.searchBinding.split(","),b=0;b<a.length&&0==a.length%2;b+=2){var e=this.win_dom.win.document.getElementById(this.formName).elements.namedItem(a[b]);if(null!=e){var d="";if(null==e.length||"SELECT"==e.tagName)d="INPUT"==e.tagName&&
"CHECKBOX"==e.type.toUpperCase()?e.checked?"1":"0":e.value;else if("RADIO"==e[0].type.toUpperCase())for(var f=0;f<e.length;f++)if(e[f].checked){d=e[f].value;break}e=$api.fn.getQueryString(this.win_dom,a[b+1],"",c);""==e||e==d||(c=$api.fn.setQueryString(this.win_dom,a[b+1],"",c),bResetPage=!0)}}1==this._wf_insert_done&&(c=$api.fn.setQueryString(this.win_dom,"page","1",c));return c}
function _wf_doReturn(c){var a=this.getDefaultReturnURL();null!=this.getReturnURL&&(a=this.getReturnURL(a));if(a==$api._gap_)if(""!=c)a=c;else return;null!=this.grid?(this.unload(),this.grid.reload()):this.win_dom.win.location.href=$api.fn.setQueryString(this.win_dom,null,null,a)}function _wf_setRequired(c,a){null==a&&(a="");this.requiredCtrls+=","+c+","+$api.fn.encodeURL(a)+","}
function _wf_autoCheckFrom(){for(var c=this.win_dom.win.document.getElementById(this.formName),a=_wf_ed(this,c.elements.namedItem("_txtFormObjects").value).split(","),b=0;b<a.length;b+=2.3>$api.fn._wf_webform_version?2:3)if(""!=a[b]&&!(null==c.elements.namedItem(a[b])||null!=c.elements.namedItem(a[b]).length&&"SELECT"!=c.elements.namedItem(a[b]).tagName)){var e=-1!=this.sDHEditorList.indexOf("\n"+a[b]+"\n"),d=this.requiredCtrls.indexOf(","+a[b]+",");e&&-1==d&&(d=this.requiredCtrls.indexOf(",dhed"+
a[b].substring(3)+","));if(-1!=d){var d=this.requiredCtrls.indexOf(",",d+1),f=this.requiredCtrls.indexOf(",",d+1),d=$api.fn.decodeURL(this.requiredCtrls.substring(d+1,f));if(""==d)if(d=c.elements.namedItem(a[b]),d.parentNode&&d.parentNode.parentNode&&"TR"==d.parentNode.parentNode.tagName){d=_wf_getInputRemark(d);if("\uff1a"==d.substring(d.length-1)||":"==d.substring(d.length-1))d=d.substring(0,d.length-1);"sel"==a[b].substring(0,3)?(d=$api.lang.form._wf_please_select.replace("@@ELEMENT",d),d=d.replace("@@FORMAT",
"")):(d=$api.lang.form._wf_please_input.replace("@@ELEMENT",d),d=a[b+1]==$api.fn._wf_integer?d.replace("@@FORMAT",$api.lang.form._wf_integer_input):a[b+1]==$api.fn._wf_double?d.replace("@@FORMAT",$api.lang.form._wf_number_input):d.replace("@@FORMAT",""))}else d=$api.lang.form._wf_input_error;f=(f=(f=a[b+1]!=$api.fn._wf_integer&&a[b+1]!=$api.fn._wf_double&&""==c.elements.namedItem(a[b]).value.replace(/ /g,""))||a[b+1]==$api.fn._wf_integer&&(""==c.elements.namedItem(a[b]).value||isNaN(c.elements.namedItem(a[b]).value)||
-1!=c.elements.namedItem(a[b]).value.indexOf(".")))||a[b+1]==$api.fn._wf_double&&(""==c.elements.namedItem(a[b]).value||isNaN(c.elements.namedItem(a[b]).value));if(e&&""==$api.fn.getTextFromHTML(c.elements.namedItem(a[b]).value).replace(RegExp("\n","gi"),"").replace(RegExp("\r","gi"),"").replace(RegExp(" ","gi"),"")){var g=this.win_dom.win.frames["dhed"+a[b].substring(3)];0==g.getEditorDOM().getElementsByTagName("IMG").length&&(f=!0)}if(f){alert(d);null!=this.beforeSetFocus&&this.beforeSetFocus(c.elements.namedItem(a[b]));
if(e)g=this.win_dom.win.frames["dhed"+a[b].substring(3)],g.getEditorWin().focus();else if("HIDDEN"!=c.elements.namedItem(a[b]).type.toUpperCase())try{c.elements.namedItem(a[b]).focus()}catch(h){}return!1}}else if((a[b+1]==$api.fn._wf_integer||a[b+1]==$api.fn._wf_double)&&""!=c.elements.namedItem(a[b]).value)if(isNaN(c.elements.namedItem(a[b]).value)||a[b+1]==$api.fn._wf_integer&&-1!=c.elements.namedItem(a[b]).value.indexOf("."))return alert($api.lang.form._wf_number_input2),c.elements.namedItem(a[b]).focus(),
!1}return!0}function _wf_ed(c,a){return"0"==c.win_dom.win.document.getElementById(c.formName).elements.namedItem("_txtDebug").value?$api.fn._ED(a):a}
function _wf_getInputRemark(c){for(var a=c.parentNode,b=0,e="",d=0;d<a.childNodes.length;d++){if(a.childNodes[d]==c){for(;b<d;b++)if("#text"==a.childNodes[b].nodeName)e+=a.childNodes[b].nodeValue;else try{e+=a.childNodes[b].innerHTML}catch(f){}break}if("INPUT"==a.childNodes[d].nodeName||"SELECT"==a.childNodes[d].nodeName||"TEXTAREA"==a.childNodes[d].nodeName)b=d+1}e=e.replace(/ /g,"").replace(/\n/g,"").replace(/\r/g,"").replace(RegExp(String.fromCharCode(8),"g"),"").replace(RegExp(String.fromCharCode(160),
"g"),"");""==e&&(e=c.parentNode.parentNode.cells[c.parentNode.cellIndex-1].innerHTML);return $api.fn.getTextFromHTML(e)}
function _wf_dealWithDHEditor(c){for(var a=this.win_dom.win.document.getElementById(this.formName),b=this.sDHEditorList.split("\n"),e=0;e<b.length;e++)if(""!=b[e]){var d=this.win_dom.win.frames["dhed"+b[e].substring(3)];if(null==d||null==d.setContent||null==d.getContent||$api.fn._IE()&&"complete"!=this.win_dom.win.document.readyState){this.win_dom.win.setTimeout("$wapper._a_web_form["+this._web_form_index+'].dealWithDHEditor("'+c+'");',!$api.fn._IE()?600:500);return}}for(e=0;e<b.length;e++)if(""!=
b[e]){var d=this.win_dom.win.frames["dhed"+b[e].substring(3)],f=a.elements.namedItem(b[e]);"submit"==c?f.value=$api.fn.getSaveFormat(this.win_dom,d.getContent()):"init"==c&&d.setContent($api.fn.getDisplayFormat(this.win_dom,f.value))}}function _wf_getHiddenFrame(){return this.win_dom.win.frames[this.win_dom.win.document.getElementById(this.formName).target]}
function _wf_dealWithDateControl2(c){for(var a=this.win_dom.win.document.getElementById(this.formName),b=0;b<a.elements.length;b++)if(!("INPUT"!=a.elements[b].tagName||"TEXT"!=a.elements[b].type.toUpperCase()))if(!(""==a.elements[b].value||null==a.elements[b].getAttribute("_TimePart")))if("beforesubmit"==c){if(-1==a.elements[b].value.indexOf(" ")){var e=a.elements[b].getAttribute("_TimePart");-1!=e.indexOf(":")?a.elements[b].value+=" "+e:eval('this.win_dom.win.document.getElementById("'+this.formName+
'").elements.namedItem("'+a.elements[b].name+'").value+=" "+'+e+".getValue();")}}else"aftersubmit"==c&&-1!=a.elements[b].value.indexOf(" ")&&(a.elements[b].value=a.elements[b].value.substring(0,a.elements[b].value.indexOf(" ")))};
