$wapper.api.include("prototype,effects,window,themes/default.css,themes/alphacube.css,themes/mac_os_x.css");var dialogWin=null,sActionScript="",_sReturnValue="",_dlg_files_web="",_dlg_files_web="function"==typeof $fn.getFilesWeb?$fn.getFilesWeb():"",bMSIE=$api.fn._IE();function _dlg_getOwnerApp(){var a=$api._gap_;a==$api._libaray_path&&(a=$api.win.$wapper.api.getQueryString("system_owner_app"));return a}function getOwnerApp(){return _dlg_getOwnerApp()}
function showDateTime(a,c,b,e){null==e&&(e="HH24:MI:SS");var f=b;null!=a&&(""==a.id&&(a.id="object_"+Math.floor(65536%Math.random())),f='_date_change("'+a.id+'");\n'+b);showFrameDialog($api._libaray_path+"/date_time.htm?date="+$api.fn.encodeURL(a?a.value:"")+"&time="+(c?1:0)+"&time_format="+$api.fn.encodeURL(e)+"&system_owner_app="+$api.fn.encodeURL(_dlg_getOwnerApp())+"&"+Math.random(),"\u65f6\u95f4/\u65e5\u671f\u9009\u62e9","dialogHeight:"+(c?320:290)+";dialogWidth:260;center:1;resizable:0",null,
f)}function _date_change(a){if(getReturnValue()&&(document.getElementById(a).value=getReturnValue(),null!=document.getElementById(a).onchange))document.getElementById(a).onchange()}
function showFrameDialog(a,c,b,e,f){var b=b.replace(/:/g,"=").replace(/;/g,"&"),g=$wp.getQueryString("dialogHeight",480,"?"+b).replace(/px/g,""),d=$wp.getQueryString("dialogWidth",320,"?"+b).replace(/px/g,""),h="1"==$wp.getQueryString("resizable",1,"?"+b),i="1"==$wp.getQueryString("fix",0,"?"+b),j="1"==$wp.getQueryString("center",1,"?"+b);$wp.getQueryString("class","alphacube","?"+b);b=$wp.getQueryString("duration","0.6","?"+b);sActionScript=null==f?"":f;i||(g>=document.body.clientHeight&&(g=document.body.clientHeight-
16),d>=document.body.clientWidth&&(d=document.body.clientWidth-16));if(j)var k=document.body.clientHeight-16>g?(document.body.clientHeight-g)/2:50,l=document.body.clientWidth-16>d?(document.body.clientWidth-d)/2:0;dialogWin=new Window("pop_"+$ap.getRandomString(16),{title:c,zIndex:1E4,minimizable:!1,maximizable:!1,top:k,left:l,width:d,height:g,className:"alphacube",resizable:h,url:$wp.setQueryString("inline","1",a),showEffectOptions:{duration:b}});dialogWin.show(!e)}
function showInfo(a,c,b){return showFrameDialog($api._libaray_path+"/showinfo.htm?msg="+(a?$api.fn.encodeURL(a):"")+"&system_owner_app="+$api.fn.encodeURL(_dlg_getOwnerApp())+"&"+Math.random(),c,b,null)}
function showInput(a,c,b,e,f,g,d){return showFrameDialog($api._libaray_path+"/inputbox.htm?prompt="+(c?$api.fn.encodeURL(c):"")+"&default="+(b?$api.fn.encodeURL(b):"")+"&format="+(e?e:"")+(null!=d?"&"+d:"")+"&max_length="+(f?f:"")+"&system_owner_app="+$api.fn.encodeURL(_dlg_getOwnerApp())+"&"+Math.random(),a,"dialogWidth:280px;dialogHeight:"+(null!=d&&-1!=d.indexOf("&additional=")?"230px":"200px")+";center:1;help:0;status:0;",null,g)}
function showColor(a,c){null==a&&(a="000000");"#"==a.substring(0,1)&&(a=a.substring(1));return showFrameDialog("color.htm?color="+a+"&system_owner_app="+$api.fn.encodeURL(_dlg_getOwnerApp())+"&"+Math.random(),"\u9009\u62e9\u989c\u8272","dialogWidth:500px;dialogHeight:280px;center:1;help:0;status:0;",null,c)}function setReturnValue(a){_sReturnValue=a;try{parent.setReturnValue(a)}catch(c){}}function getReturnValue(){return _sReturnValue}
function closeDialog(){if(""!=parent.sActionScript)try{eval((-1==parent.sActionScript.indexOf("parent.")?"parent.":"")+parent.sActionScript)}catch(a){alert("e="+a)}parent.dialogWin.close()};
