var _oCurDropDown=null,_aMouseupEvent=[],onHideDropDown=null;
function createDropDrownFrame(a,b,e,d,f){var g=_getDropDownNameOfObj(a),c=document.getElementById(g);if(null==c){c=document.createElement("DIV");c.id=g;c.style.display="none";c.style.position="absolute";c.style.backgroundColor="white";c.style.zIndex="10000";null==f&&(f=a);if(null==f.id||""==f.id)f.id="object_"+Math.floor(65536*Math.random());a.setAttribute("DropdownAlignObject",f.id);c.style.width=e;c.style.height=d;c.innerHTML='<iframe style="width:100%;height:100%;position:absolute;left:0;top:0;z-index:9998" border=0 frameborder=0></iframe><div style="width:100%;height:100%;position:absolute;left:0;top:0;z-index:9999">'+b+
"</div>";document.body.appendChild(c);c=document.getElementById(g);for(a=f;null!=a&&"BODY"!=a.tagName;a=a.offsetParent)null==a.onscroll&&(a.onscroll=onDropwownScrollEvent)}return c}
function showDropDownFrame(a){var b=a.getAttribute("DropDownDIV"),b=document.getElementById(b);if(""==b.style.display&&b.getAttribute("DropdownOwner")==a.id){if("function"!=typeof onHideDropDown||onHideDropDown(b))b.style.display="none"}else{b.setAttribute("DropdownOwner",a.id);for(var a=document.getElementById(a.getAttribute("DropdownAlignObject")),e=0,d=a.offsetHeight,f=0,g=0,c=a;null!=c&&"BODY"!=c.tagName;c=c.offsetParent)e+=c.offsetLeft,d+=c.offsetTop,f+=c.scrollTop,g+=c.scrollLeft;b.style.display=
"";e-=g;d-=f;b.style.left=e;d+b.offsetHeight>document.body.scrollTop+document.body.clientHeight&&d-a.offsetHeight-b.offsetHeight>document.body.scrollTop&&(d=d-a.offsetHeight-b.offsetHeight);b.style.top=d;b.setAttribute("DropdownX",e+g);b.setAttribute("DropdownY",d+f);_oCurDropDown=b}}function hideDropDownFrame(){if(null!=_oCurDropDown&&("function"!=typeof onHideDropDown||onHideDropDown(_oCurDropDown)))_oCurDropDown.style.display="none"}
function destroyDropDownFrame(a){hideDropDownFrame();a=_getDropDownNameOfObj(a);(a=document.getElementById(a))&&a.removeNode(!0)}function _getDropDownNameOfObj(a){if(null!=a.getAttribute("DropDownDIV"))return a.getAttribute("DropDownDIV");var b="_div_drop_down_"+Math.floor(65536*Math.random());a.setAttribute("DropDownDIV",b);return b}function registMouseUpEvent(a){_aMouseupEvent[_aMouseupEvent.length]=a}
document.onmouseup=function(a){-1!=window.navigator.appVersion.indexOf("MSIE")&&(a=window.event);for(var b=0;b<_aMouseupEvent.length;b++)_aMouseupEvent[b](a)};
registMouseUpEvent(function(a){if(_oCurDropDown){for(a=-1!=window.navigator.appVersion.indexOf("MSIE")?a.srcElement:a.target;null!=a&&"HTML"!=a.tagName;a=a.parentNode)if(a==_oCurDropDown||_oCurDropDown.getAttribute("DropdownOwner")==a.id||null!=a.onclick&&-1!=a.onclick.toString().indexOf("showDropDownFrame("+_oCurDropDown.getAttribute("DropdownOwner")+")"))return;hideDropDownFrame()}});
function onDropwownScrollEvent(){if(null!=_oCurDropDown){for(var a=document.getElementById(_oCurDropDown.getAttribute("DropdownOwner")),b=0,e=0,a=document.getElementById(a.getAttribute("DropdownAlignObject"));null!=a&&"BODY"!=a.tagName;a=a.offsetParent)b+=a.scrollTop,e+=a.scrollLeft;var a=_oCurDropDown.getAttribute("DropdownX"),d=_oCurDropDown.getAttribute("DropdownY");_oCurDropDown.style.left=a-e;_oCurDropDown.style.top=d-b}};
