document.write("<style>\n");document.write(".list_bilder_header{background:#F9F9F9;height:26px;}\n");document.write(".list_bilder_row{background:#FFFFFF;height:26px;}\n");document.write(".list_bilder_table{background:#C0C0C0}\n");document.write(".list_bilder_blank{width:100%;border:none;border-bottom:1px solid black;background:none}\n");document.write(".list_bilder_blank_readonly{width:100%;border:none;background:none}\n");document.write("</style>");
var _LB_DIALOG_INPUT=1,_LB_ROW_INPUT=2,_LB_DELETE_LINK=4,_LB_INSERT_LINK=8,_LB_APPEND_LINK=16,_LB_UPDOWN_LINK=32,_LB_CUSTOM_LINK=64,_LB_LANGUAGE="_list_builder",_a_list_builder=[];
function ListBuilder(a){if(null==a||""==a||document.getElementById(a))a="table_"+Math.floor(65536*Math.random());this.sTableId=a;this.aHeader=[];this.aHeaderWidth=[];this.aCellRW=[];this.aAttribute=[];this.aData=[];this.sIdentity="";this.sStyleCSS="list_bilder";this.nStyle=_LB_DIALOG_INPUT+_LB_DELETE_LINK+_LB_APPEND_LINK;this.sUnDeleteData=this.sCustomLink="";this.setStyle=_lb_setStyle;this.setCustomLink=_lb_setCustomLink;this.addHeader=_lb_addHeader;this.addAttribute=_lb_addAttribute;this.sListData=
"";this.setListData=_lb_setListData;this.addRowByData=_lb_addRowByData;this.getTableId=_lb_getTableId;this.getHTML=_lb_getHTML;this.doInputDialog=_lb_empty_input;this.afterDeleteRow=this.beforeDeleteRow=null;this.insertRow=_lb_insertRow;this.beforeInsertRow=null;this.checkRowData=_lb_defaultDataCheck;this.resetInput=_lb_resetInputDefault;this.getListData=_lb_getListData;this.checkListData=_lb_defaultDataCheck;this.getCellData=_lb_getCellData;this.getCellDataDefault=_lb_getCellDataDefault;this.getCellHTML=
_lb_getCellHTML;this.getCellHTMLDefault=_lb_getCellHTMLDefault;this.doLanguageBind=_lb_doLanguageBind;_a_list_builder[_a_list_builder.length]=this;this.nListBuilderIndex=_a_list_builder.length-1}function _lb_setStyle(a){this.nStyle=a}function _lb_setCustomLink(a){this.sCustomLink=a}
function _lb_addHeader(a,c,f,b){this.aHeader[this.aHeader.length]=a;this.aHeaderWidth[this.aHeaderWidth.length]=c;null==b&&(b=!1);this.aCellRW[this.aCellRW.length]=b;f&&(this.sIdentity="_list_builder_cell_data_"+(this.aHeader.length-1));return this.aHeader.length-1}function _lb_addAttribute(a,c){this.aAttribute[this.aAttribute.length]=a;c&&(this.sIdentity=a)}function _lb_setListData(a,c){"object"==typeof a?this.aData=a:"string"==typeof a&&(this.aData=a.split(c))}
function _lb_addRowByData(a,c,f){var b="",d="",e="";null==f&&(f=document.getElementById(this.sTableId).rows.length-1);for(var a=a.split(c),g=c=0;g<a.length&&0==a.length%(this.aHeader.length+this.aAttribute.length);g+=this.aHeader.length+this.aAttribute.length){d=b="";0==this.sIdentity.indexOf("_list_builder_cell_data_")&&(b="tr_"+this.sTableId+"_"+a[g+this.aAttribute.length+parseInt(this.sIdentity.substring(this.sIdentity.lastIndexOf("_")+1))]);for(var h=0;""==b&&h<this.aAttribute.length;h++)this.aAttribute[h]==
this.sIdentity&&""==b&&(b="tr_"+this.sTableId+"_"+a[g+h]);""==b&&(b="tr_"+Math.floor(65536*Math.random()));if(document.getElementById(b))c++;else{var i=document.getElementById(this.sTableId).insertRow(f+g/(this.aHeader.length+this.aAttribute.length)-c);i.setAttribute("id",b);var j=null;i.className=this.sStyleCSS+"_row";for(h=0;h<this.aAttribute.length;h++)i.setAttribute(this.aAttribute[h],a[g+h]);for(var k=[],h=0;h<this.aHeader.length+this.aAttribute.length;h++)k[k.length]=a[g+h];for(h=0;h<this.aHeader.length;h++)j=
i.insertCell(i.cells.length),j.width=this.aHeaderWidth[h],e=this.getCellHTML(h,a[g+this.aAttribute.length+h],k),j.innerHTML=e;(this.nStyle&_LB_INSERT_LINK)==_LB_INSERT_LINK&&(d+='&nbsp;<a href="javascript:" id=aLbInsert name=aLbInsert>\u63d2\u5165</a>');(this.nStyle&_LB_DELETE_LINK)==_LB_DELETE_LINK&&(d+='&nbsp;<a href="javascript:_lb_deleteRow(_a_list_builder['+this.nListBuilderIndex+"],'"+b+"')\" id=aLbDelete name=aLbDelete>\u5220\u9664</a>");(this.nStyle&_LB_UPDOWN_LINK)==_LB_UPDOWN_LINK&&(d+=
'&nbsp;<a href="javascript:_lb_moveRow(_a_list_builder['+this.nListBuilderIndex+"],'"+b+"',-1)\" id=aLbMoveUp name=aLbMoveUp>\u4e0a\u79fb</a>",d+='&nbsp;<a href="javascript:_lb_moveRow(_a_list_builder['+this.nListBuilderIndex+"],'"+b+"',1)\" id=aLbMoveDown name=aLbMoveDown>\u4e0b\u79fb</a>");""!=d&&(i.insertCell(i.cells.length).innerHTML="<nobr>"+d+"</nobr>")}}"undefined"!=typeof sALbNew&&this.doLanguageBind()}
function _lb_getHTML(){for(var a="",c="",f="",b="<table class="+this.sStyleCSS+"_table id="+this.sTableId+" cellpadding=0 cellspacing=1>",b=b+("<TR class="+this.sStyleCSS+"_header>"),d=0;d<this.aHeader.length;d++)b+='<td width="'+this.aHeaderWidth[d]+'">&nbsp;'+this.aHeader[d];if((this.nStyle&_LB_DELETE_LINK)==_LB_DELETE_LINK||(this.nStyle&_LB_INSERT_LINK)==_LB_INSERT_LINK)b+="<td width=80>&nbsp;<span id=spanLbOp name=spanLbOp>\u64cd\u4f5c</span>";for(d=0;d<this.aData.length&0==this.aData.length%
(this.aHeader.length+this.aAttribute.length);d+=this.aHeader.length+this.aAttribute.length){c="";b+="<TR class="+this.sStyleCSS+"_row ";a="";0==this.sIdentity.indexOf("_list_builder_cell_data_")&&(a="tr_"+this.sTableId+"_"+this.aData[d+this.aAttribute.length+parseInt(this.sIdentity.substring(this.sIdentity.lastIndexOf("_")+1))]);for(var e=0;e<this.aAttribute.length;e++)b+=this.aAttribute[e]+'="'+this.aData[d+e]+'" ',this.aAttribute[e]==this.sIdentity&&""==a&&(a="tr_"+this.sTableId+"_"+this.aData[d+
e]);""==a&&(a="tr_"+Math.floor(65536*Math.random()));for(var b=b+("id="+a+">"),g=[],e=0;e<this.aHeader.length+this.aAttribute.length;e++)g[g.length]=this.aData[d+e];for(e=0;e<this.aHeader.length;e++)f=this.getCellHTML(e,this.aData[d+this.aAttribute.length+e],g,this.aCellRW[e]),b+='<td width="'+this.aHeaderWidth[e]+'">'+f;(this.nStyle&_LB_INSERT_LINK)==_LB_INSERT_LINK&&(c+='&nbsp;<a href="javascript:" id=aLbInsert name=aLbInsert>\u63d2\u5165</a>');(this.nStyle&_LB_DELETE_LINK)==_LB_DELETE_LINK&&(c=
-1==(","+this.sUnDeleteData+",").indexOf(","+a.replace("tr_"+this.sTableId+"_","")+",")?c+('&nbsp;<a href="javascript:_lb_deleteRow(_a_list_builder['+this.nListBuilderIndex+"],'"+a+"')\" id=aLbDelete name=aLbDelete>\u5220\u9664</a>"):c+"&nbsp;");(this.nStyle&_LB_UPDOWN_LINK)==_LB_UPDOWN_LINK&&(c+='&nbsp;<a href="javascript:_lb_moveRow(_a_list_builder['+this.nListBuilderIndex+"],'"+a+"',-1)\" id=aLbMoveUp name=aLbMoveUp>\u5411\u4e0a</a>",c+='&nbsp;<a href="javascript:_lb_moveRow(_a_list_builder['+
this.nListBuilderIndex+"],'"+a+"',1)\" id=aLbMoveDown name=aLbMoveDown>\u5411\u4e0b</a>");""!=c&&(b+="<td><nobr>"+c+"</nobr>")}c="&nbsp;";if((this.nStyle&_LB_DIALOG_INPUT)==_LB_DIALOG_INPUT||(this.nStyle&_LB_ROW_INPUT)==_LB_ROW_INPUT)b+="<tr class="+this.sStyleCSS+"_row>";if((this.nStyle&_LB_DIALOG_INPUT)==_LB_DIALOG_INPUT)(this.nStyle&_LB_APPEND_LINK)==_LB_APPEND_LINK&&(c+='<a href="javascript:_a_list_builder['+this.nListBuilderIndex+'].doInputDialog()" id=aLbNew name=aLbNew>\u6dfb\u52a0</a>'),(this.nStyle&
_LB_CUSTOM_LINK)==_LB_CUSTOM_LINK&&(c+=this.sCustomLink),b+="<td colspan="+this.aHeader.length+" align=right>&nbsp;<td>"+c;else if((this.nStyle&_LB_ROW_INPUT)==_LB_ROW_INPUT){for(d=0;d<this.aHeader.length;d++)b+="<td>"+this.getCellHTML(d,"","");(this.nStyle&_LB_APPEND_LINK)==_LB_APPEND_LINK&&(c+='<a href="#LB" onclick="_a_list_builder['+this.nListBuilderIndex+'].insertRow();" id=aLbNew name=aLbNew>\u6dfb\u52a0</a>');b+="<td>"+c}return b+"</table>"}function _lb_getTableId(){return this.sTableId}
function _lb_getListData(a,c){var f="";null==c&&(c="\n");a=""+a;if(!((this.nStyle&_LB_ROW_INPUT)==_LB_ROW_INPUT&&null!=this.checkListData&&!this.checkListData())){var a=a.replace(/\n/g,","),b=a.split(","),d=document.getElementById(this.sTableId).rows.length-1;0==this.nStyle&&(d=document.getElementById(this.sTableId).rows.length);for(var e=1;e<d;e++){document.getElementById(this.sTableId);for(var g=0;g<b.length;g++){var h="";""!=b[g]&&(h=isNaN(b[g])?document.getElementById(this.sTableId).rows[e].getAttribute(b[g]):
this.getCellData(document.getElementById(this.sTableId).rows[e].cells[parseInt(b[g])]),null==h&&(h=""),f+=(1==e&&0==g?"":c)+h)}}return f}}function _lb_deleteRow(a,c){var f=document.getElementById(c);if(null==a.beforeDeleteRow||a.beforeDeleteRow(f))f.parentNode.parentNode.deleteRow(f.rowIndex),null!=a.afterDeleteRow&&a.afterDeleteRow(null)}
function _lb_moveRow(a,c,f){var b=document.getElementById(a.getTableId()),d=document.getElementById(c);if(1==d.rowIndex&&-1==f)a="\u5df2\u7ecf\u5728\u9876\u7aef\u4e86\uff0c\u4e0d\u80fd\u4e0a\u79fb","string"==typeof sLbTopError&&(a=sLbTopError),alert(a);else if(d.rowIndex==b.rows.length-2&&1==f)alert(sLbBottomError);else{for(var b="",e=0;e<a.aAttribute.length;e++)b+=(0==e?"":"\n")+d.getAttribute(a.aAttribute[e]);for(e=0;e<a.aHeader.length;e++)b+=(0!=e||""!=b?"\n":"")+a.getCellData(d.cells[e]);d=d.rowIndex;
_lb_deleteRow(a,c);a.addRowByData(b,"\n",-1==f?d-1:d+1)}}
function _lb_insertRow(a){var c=null,c=null!=a?document.getElementById(a):document.getElementById(this.sTableId).rows[document.getElementById(this.sTableId).rows.length-1];if(null!=this.checkRowData&&!this.checkRowData(c)||null!=this.beforeInsertRow&&!this.beforeInsertRow(c))return!1;for(var f=a="",b=0;b<this.aAttribute.length;b++)f=c.getAttribute(this.aAttribute[b]),null==f&&(f=""),a+=(0==b?"":"\n")+f;for(b=0;b<this.aHeader.length;b++)a+=(0!=b||0!=this.aAttribute.length?"\n":"")+this.getCellData(c.cells[b]);
this.resetInput(c);this.addRowByData(a,"\n",c.rowIndex);return!0}function _lb_resetInputDefault(a){if(a.rowIndex==document.getElementById(this.sTableId).rows.length-1&&this.getCellHTML==_lb_getCellHTML)for(var c=0;c<this.aHeader.length;c++)a.cells[c].getElementsByTagName("INPUT")[0].value=""}
function _lb_defaultDataCheck(a){var c=!1;if((this.nStyle&_LB_DELETE_LINK)==_LB_DELETE_LINK||(this.nStyle&_LB_INSERT_LINK)==_LB_INSERT_LINK)c=!0;for(var f=document.getElementById(this.sTableId),b=a?a.rowIndex:1;b<(a?a.rowIndex+1:f.rows.length-1);b++)for(var d=0;d<f.rows[b].cells.length-(c?1:0)&&0<f.rows[b].cells[d].getElementsByTagName("INPUT").length;d++){var e=f.rows[b].cells[d].getElementsByTagName("INPUT")[0],g=e.getAttribute("AllowEmpty");null==g&&(g="0");if("1"!=g&&""==e.value.replace(/ /g,
""))return a="\u8bf7\u8f93\u5165 {0} \uff01","string"==typeof sLbPleaseInput&&(a=sLbPleaseInput),alert(a.replace("{0}",this.aHeader[d])),"hidden"!=e.type.toLowerCase()&&"none"!=e.style.display&&e.focus(),!1}return!0}function _lb_getCellHTML(a,c,f,b){return this.getCellHTMLDefault(c,b)}function _lb_getCellData(a){return this.getCellDataDefault(a)}
function _lb_getCellHTMLDefault(a,c){return(this.nStyle&_LB_DIALOG_INPUT)==_LB_DIALOG_INPUT?(0!=a.indexOf("<")&&(a="&nbsp;"+a),a):"<input class="+this.sStyleCSS+(c?"_blank_readonly":"_blank")+" "+(c?"readOnly":"")+' value="'+a.replace(/\"/g,"&quot;")+'" onkeyup=_listBuilderInput_onkeyup(_a_list_builder['+this.nListBuilderIndex+"],event)>"}
function _lb_getCellDataDefault(a){return(this.nStyle&_LB_DIALOG_INPUT)==_LB_DIALOG_INPUT?getInnerText(a):0<a.getElementsByTagName("INPUT").length?a.getElementsByTagName("INPUT")[0].value:""}
function _listBuilderInput_onkeyup(a,c){if(13==c.keyCode){for(var f=null,b=null,d=$api.fn._IE()?c.srcElement:c.target,e=null;"TABLE"!=d.tagName;)null==f&&"TD"==d.tagName&&(f=d),null==b&&"TR"==d.tagName&&(b=d),d=d.parentNode;f.cellIndex==b.cells.length-2?b.rowIndex==d.rows.length-1?a.insertRow():e=d.rows[b.rowIndex+1].cells[0]:e=b.cells[f.cellIndex+1];if(e&&1==e.getElementsByTagName("INPUT").length)try{e.getElementsByTagName("INPUT")[0].focus()}catch(g){}}}function _lb_empty_input(){}
function _lb_doLanguageBind(){$wapper.api.doLanguageBinding("a_lb_new,a_lb_insert,a_lb_delete,a_lb_move_up,a_lb_move_down,span_lb_op")}"string"!=typeof sLbPleaseInput&&$wapper.api.includeLangBundle(_LB_LANGUAGE);
