var _JS_Popup_ID=0,_oCurrectPopup=null,_timer_for_popup=null;function Popup(){this.id="_JS_Popup_"+_JS_Popup_ID++;this.width=0;this.subItems=[];this.parentItem=null;this.addItem=_AddPopupItem;this.addSeparator=_addSeparatorItem;this.popup=_showPopup;this.hide=_hidePopup;this.handleKeyEvent=_handleKeyEvent;this.handleMouseDownEvent=_handleMouseDownEvent;this.getHTML=_getPopupCode}
function PopupItem(a,c,b,d){this.icon=null==a?"":a;this.caption=c;this.script=b;this.type=d?d:"";this.id=null;b=c.indexOf("&");a=50;this.accessKey=-1!=b&&b!=c.length-1?c.substring(b+1,b+2).toUpperCase():"";for(b=0;b<c.length;b++)128<c.charCodeAt(b)?a+=15:b<c.length-1&&"&"==c.charCodeAt(b)?b++:a+=7;100>a&&(a=100);this.width=a;this.SeparatorLine=!1;this.subMenu=null;this.setSubMenu=_setSubMenu;this.addItem=_addSubItemToPopupItem;this.addSeparator=_addSeparatorItem2;this.setEnabled=_setPopupItemEnabled;
this.setChecked=_setPopupItemChecked2;this.getChecked=_getCheckedState}function _AddPopupItem(a){if("-"==a.caption&&0<this.subItems.length)this.subItems[this.subItems.length-1].SeparatorLine=!0;else return a.id=this.id+"_"+this.subItems.length,this.subItems[this.subItems.length]=a,this.width<a.width&&(this.width=a.width),a}function _addSeparatorItem(){return this.addItem(new PopupItem(null,"-"))}function _setSubMenu(a){this.subMenu=a;a.parentItem=this;return a}
function _addSubItemToPopupItem(a){null==this.subMenu&&this.setSubMenu(new Popup);return this.subMenu.addItem(a)}function _addSeparatorItem2(){return this.addItem(new PopupItem(null,"-"))}function _showPopup(a,c){popupMenu(this,a,c)}
function popupMenu(a,c,b,d){var e=_oCurrectPopup;hidePopup(a);a=document.getElementById(a.id);a.style.display="";if(d){for(var b=c=0,f=d;f;)c+=f.offsetLeft,b+=f.offsetTop,f=f.offsetParent;c=c+d.offsetWidth+a.offsetWidth>document.body.clientWidth?c-a.offsetWidth:c+d.offsetWidth;b+a.offsetHeight-document.body.scrollTop>document.body.clientHeight&&(b=b-a.offsetHeight+d.offsetHeight)}else c=c+a.offsetWidth>document.body.clientWidth?c-a.offsetWidth+document.body.scrollLeft:c+document.body.scrollLeft,b=
b+a.offsetHeight>document.body.clientHeight?b-a.offsetHeight+document.body.scrollTop:b+document.body.scrollTop,a.style.zIindex=1E4;a.style.left=c;a.style.top=b;_adjustYPositionOfPopup(a);e&&(a.style.zIndex=parseInt(e.style.zIndex)+1);_oCurrectPopup=a}function _hidePopup(){hidePopup(this)}function hidePopup(a){document.getElementById(a.id).currectItem&&_dishighlightItem(document.getElementById(document.getElementById(a.id).currectItem));document.getElementById(a.id).style.display="none"}
function _getPopupCode(a,c){var b="";null==a&&(a=this.id);for(var d="<div id="+this.id+" menuWidth="+this.width+" itemsCount="+this.subItems.length+' parentItemID="'+(this.parentItem?this.parentItem.id:"")+'" topPopupID='+a+' isPopup=1 onselectstart="return false" style="border:solid black 1px;position:absolute;font-size:1px;cursor:default;z-Index:10000;width:'+this.width+";display:none;filter:progid:DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='lightgrey', Positive='true')\">",d=d+
'<table border=0 cellpadding=0 cellspacing=0 height="100%" style="font-size:1px;">'+('<tr style="display:none;height;20px;" isItemArrow=1 id='+this.id+"_up_arrow  onmouseover=_itemArrow_onmousemove('"+this.id+'\',-1) onmouseout=window.clearTimeout(_timer_for_popup)><td width=20 bgColor=#DBD8D1>&nbsp;<td  bgColor=#F9F8F7 align=center valign=top colSpan=2 style="font-size:9pt;font-family:webdings;"><span style="margin-top:-2px;">5</span>'),d=d+'<tr height=3px; style="font-size:1px;"><td width=20 bgColor=#DBD8D1><td colspan=2 bgColor=#F9F8F7 align=center>',
e=0;e<this.subItems.length;e++){var d=d+("<tr id="+this.subItems[e].id+" popupID="+this.id+' accessKey="'+this.subItems[e].accessKey+'" enabledState=1 height="'+("-"==this.subItems[e].caption?10:20)+'px" '+(this.subItems[e].subMenu?"subMenuID="+this.subItems[e].subMenu.id:"")+' itemStyle="'+this.subItems[e].type+'" itemGroup=1 onmouseover=_highlightItem(this) ScriptToExec="'+(this.subItems[e].script?this.subItems[e].script:"")+'" onmouseup="_popupitem_onclick(this);">'),d=d+'<td bgColor=#DBD8D1 width=20 align=center style="border-top:solid #DBD8D1 1px;border-left:solid #DBD8D1 1px;border-bottom:solid #DBD8D1 1px;">',
d="-"!=this.subItems[e].caption&&""!=this.subItems[e].icon?d+('<img src="'+this.subItems[e].icon+'" width=16 height=16 align=absmiddle>'):d+"<div style=width:20px>&nbsp;</div>",d=d+("<td bgColor=#F9F8F7 width="+(this.width-36)+' style="font-size:9pt;border-top:solid #F9F8F7 1px;border-bottom:solid #F9F8F7 1px;padding-left:3px;">&nbsp;'),f=this.subItems[e].caption,g=f.indexOf("&");-1!=g&&(f=f.substring(0,g)+"<u>"+f.substring(g+1,g+2)+"</u>"+f.substring(g+2));d+="<nobr>"+f.replace(/ /g,"&nbsp;")+"</nobr>";
d+='<td width=16 bgColor=#F9F8F7 style="border-top:solid #F9F8F7 1px;border-bottom:solid #F9F8F7 1px;border-right:solid #F9F8F7 1px;">';null==this.subItems[e].subMenu||c?d+="&nbsp;":(b+=this.subItems[e].subMenu.getHtmlText(a),d+='<span style="font-family:webdings;font-size:9pt;">4</span>');d+='<tr height=3px;><td width=20 bgColor=#DBD8D1><td colspan=2 bgColor=#F9F8F7 align=right style="font-size:1px;">';d=this.subItems[e].SeparatorLine?d+'<div style="width:95%;height:1px;border-bottom:solid gray 1px;margin-top:-2px;"></div>':
d+"&nbsp;"}d+='<tr style="display:none;height;20px;" isItemArrow=1 id='+this.id+"_down_arrow onmouseover=_itemArrow_onmousemove('"+this.id+'\',1)  onmouseout=window.clearTimeout(_timer_for_popup)><td width=20 bgColor=#DBD8D1>&nbsp;<td  bgColor=#F9F8F7 align=center vAlign=bottom colSpan=2 style="font-size:9pt;font-family:webdings;"><span style="margin-top:-2px;">6</span>';return d+"</table></div>"+b}function _writePopup(a){document.write(this.getHtmlText(a))}
function _highlightItem(a){document.getElementById(a.popupID).currectItem!=a.id&&(null!=document.getElementById(a.popupID).currectItem&&_dishighlightItem(document.getElementById(document.getElementById(a.popupID).currectItem)),"1"!=a.enabledState||0<a.all.tags("HR").length||("1"!=a.highlightState&&(a.cells(0).bgColor="#B5BCD2",a.cells(0).style.borderTop="solid black 1px",a.cells(0).style.borderLeft="solid black 1px",a.cells(0).style.borderBottom="solid black 1px",a.cells(1).bgColor="#B5BcD2",a.cells(1).style.borderTop=
"solid black 1px",a.cells(1).style.borderBottom="solid black 1px",a.cells(2).bgColor="#B5BcD2",a.cells(2).style.borderTop="solid black 1px",a.cells(2).style.borderRight="solid black 1px",a.cells(2).style.borderBottom="solid black 1px"),a.highlightState="1",document.getElementById(a.popupID).currectItem=a.id,a.subMenuID&&(_timer_for_popup=window.setTimeout("popupMenu(document.getElementById('"+a.subMenuID+"'),null,null,document.getElementById('"+a.id+"'));",250)),_oCurrectPopup=document.getElementById(a.popupID)))}
function _dishighlightItem(a){0==a.all.tags("HR").length&&(a.cells(0).bgColor="#DBD8D1",a.cells(0).style.borderTop="solid #DBD8D1 1px",a.cells(0).style.borderLeft="solid #DBD8D1 1px",a.cells(0).style.borderBottom="solid #DBD8D1 1px",a.cells(1).bgColor="#F9F8F7",a.cells(1).style.borderTop="solid #F9F8F7 1px",a.cells(1).style.borderBottom="solid #F9F8F7 1px",a.cells(2).bgColor="#F9F8F7",a.cells(2).style.borderTop="solid #F9F8F7 1px",a.cells(2).style.borderBottom="solid #F9F8F7 1px",a.cells(2).style.borderRight=
"solid #F9F8F7 1px");a.highlightState="0";document.getElementById(a.popupID).currectItem=null;a.subMenuID&&(_timer_for_popup&&window.clearTimeout(_timer_for_popup),hidePopup(document.getElementById(a.subMenuID)))}
function _popupitem_onclick(a){var c=null;window.event&&(c=event.srcElement);for(;c&&!("1"==c.isItemArrow);){if(null!=c.subMenuID){_oCurrectPopup.currectItem=null;_highlightItem(a);return}c=c.parentElement}null==c&&hidePopup(document.getElementById(document.getElementById(a.popupID).topPopupID));"1"==a.enabledState&&(_setPopupItemChecked(a),a.ScriptToExec&&window.execScript(a.ScriptToExec))}function _setPopupItemChecked2(a){_setPopupItemChecked(document.getElementById(this.id),a)}
function _setPopupItemChecked(a,c){var b=null;null!=c&&(b=c?"1":"0");if(!(""==a.itemStyle||null==a.itemStyle))if("checkbox"==a.itemStyle)null==b&&(b=a.checkedState,null==b&&(b="0"),b=1-parseInt(b)),a.checkedState=b,0==a.cells(0).all.tags("IMG").length&&(a.cells(0).innerHTML="0"==b?"&nbsp;":'<div style="border:solid black 1px;font-size:9pt;width:16px;height:18px;overflow:hidden;background:#D4D5D8;padding-top:1px;padding-left:1px;padding-bottom:1px"><span style=font-weight:bold>\u221a</span></div>');
else{for(var b=document.getElementById(a.popupID),d=0;d<b.itemsCount;d++){var e=document.getElementById(b.id+"_"+d);e.itemGroup==a.itemGroup&&(e.cells(0).innerHTML="&nbsp;")}a.checkedState=1;a.cells(0).innerHTML='<div style="border:solid black 1px;font-size:9pt;width:16px;height:18px;overflow:hidden;background:#D4D5D8;padding-top:1px;padding-left:1px;padding-bottom:1px"><span style=font-weight:bold>\u221a</span></div>'}}
function _getCheckedState(){return"1"==document.getElementById(this.id).checkedState}function _setPopupItemEnabled(a){var c=null,b=document.getElementById(this.id);null!=a?c=a?"1":"0":(c=b.enabledState,c=""+(1-parseInt(c)));0<b.all.tags("IMG").length&&(b.all.tags("IMG")[0].style.filter="1"==c?"":"gray");b.style.color="1"==c?"black":"gray";b.enabledState=c}
function _handleKeyEvent(a){if(!_oCurrectPopup||"none"==_oCurrectPopup.style.display)return!1;switch(a.keyCode){case 13:if(a=_oCurrectPopup.currectItem){if(document.getElementById(_oCurrectPopup.currectItem).subMenuID)return _handleKeyEvent(new function(){this.keyCode=39});this.hide();try{document.getElementById(a).onmouseup()}catch(c){}}return!0;case 39:return _oCurrectPopup.currectItem&&(a=document.getElementById(_oCurrectPopup.currectItem),a.subMenuID&&popupMenu(document.getElementById(a.subMenuID),
null,null,a)),!0;case 37:case 27:var b=_oCurrectPopup.parentItemID;if(!b&&37==a.keyCode)break;hidePopup(_oCurrectPopup);b&&(_oCurrectPopup=document.getElementById(document.getElementById(b).popupID));return!0;case 38:return b=_getNextPopupItem(-1),_scrollItemIntoView(b),_highlightItem(b),!0;case 40:return b=_getNextPopupItem(1),_scrollItemIntoView(b),_highlightItem(b),!0;default:for(var d=0;;){b=document.getElementById(_oCurrectPopup.id+"_"+d);if(!b)break;if(b.accessKey==String.fromCharCode(a.keyCode)&&
"1"==b.enabledState){if(b.subMenuID)_highlightItem(b);else try{this.hide(),b.onmouseup()}catch(e){}return!0}d++}}return!1}function _handleMouseDownEvent(a){for(a=a.srcElement;a;){if("1"==a.isItemArrow||"1"==a.isPopup||null!=a.subMenuID)return!1;a=a.parentElement}this.hide();return!1}
function _getNextPopupItem(a){if(_oCurrectPopup){var c=_oCurrectPopup,b=c.currectItem;if(null==b)return-1==a?document.getElementById(c.id+"_"+(parseInt(c.itemsCount)-1)):document.getElementById(c.id+"_0");for(var d=b=parseInt(b.substring(b.lastIndexOf("_")+1));;){d+=a;0<a&&d>parseInt(c.itemsCount)-1&&(d=0);-1==a&&0>d&&(d=parseInt(c.itemsCount)-1);if(d==b)break;var e=document.getElementById(c.id+"_"+d);if(e&&!(0<e.all.tags("HR").length||"1"!=e.enabledState))break}return document.getElementById(c.id+
"_"+d)}}function _adjustYPositionOfPopup(a){a.style.posTop<document.body.scrollTop&&(a.style.posTop=document.body.scrollTop);23*parseInt(a.itemsCount)>document.body.clientHeight&&_scrollPopupItem(a,0)}
function _scrollPopupItem(a,c){var b=parseInt(document.body.clientHeight/23)-1;null==a.maxScrollTop&&(a.maxScrollTop=parseInt(a.itemsCount)-b,0>parseInt(a.maxScrollTop)&&(a.maxScrollTop=0));var c=0>c?0:c,c=c>=parseInt(a.maxScrollTop)?parseInt(a.maxScrollTop):c,b=c+b,d=document.getElementById(a.id+"_up_arrow"),e=document.getElementById(a.id+"_down_arrow");0<c?(b--,d.style.display=""):d.style.display="none";b<parseInt(a.itemsCount)-1?(b--,e.style.display=""):e.style.display="none";for(d=0;d<parseInt(a.itemsCount);d++)e=
document.getElementById(a.id+"_"+d).rowIndex,a.all.tags("TABLE")[0].rows(e).style.display=d<c||d>b?"none":"",a.all.tags("TABLE")[0].rows(e+1).style.display=d<c||d>b?"none":"";a.scrollIndex=c;-1!=window.navigator.appVersion.indexOf("MSIE 5.0")&&(a.style.height="1px");a.style.posTop=document.body.scrollTop+(document.body.clientHeight-a.offsetHeight)/2}
function _itemArrow_onmousemove(a,c){_timer_for_popup&&window.clearTimeout(_timer_for_popup);_scrollPopupItem(document.getElementById(a),parseInt(document.getElementById(a).scrollIndex)+c);_timer_for_popup=window.setTimeout("_itemArrow_onmousemove('"+a+"',"+c+")",80)}
function _scrollItemIntoView(a){if("none"==a.style.display){var c=document.getElementById(a.popupID),a=parseInt(a.id.substring(a.id.lastIndexOf("_")+1));if(a<parseInt(c.scrollIndex))_scrollPopupItem(c,a);else{var b=parseInt(document.body.clientHeight/23)-1;_scrollPopupItem(c,a-b+2)}}};
