var _tab_pages_=[];
function TabPage(){_tab_pages_[_tab_pages_.length]=this;this.tabPageId=_tab_pages_.length-1;this.aTab=[];this.selectedIndex=0;this.padding="30px";this.tab_padding="";this.length=0;this.align="left";this.event="click";this.setEventHandle=function(a){this.event=a};this.setAlign=function(a){this.align=a};this.setPadding=function(a){this.padding=a};this.setTabPadding=function(a){this.tab_padding=a};this.add=function(a,b,c,d){this.aTab[this.aTab.length]=new Tab(this,a,b,c,d);if(1==c){for(a=0;a<this.aTab.length-
1;a++)this.aTab[a].status=0;this.selectedIndex=this.aTab.length-1}this.length++;return this.aTab[this.aTab.length-1]};this.getHTML=function(){for(var a="<table cellpadding=0 cellspacing=0 width=100%><tr><td "+("left"==this.align?" width="+this.padding+" ":"")+' style="border-bottom:solid '+this.borderColor+' 1px" id=_tab_page_'+this.tabPageId+">&nbsp;",b=0;b<this.aTab.length;b++)0<b&&""!=this.tab_padding&&(a+="<td width="+this.tab_padding+' style="border-bottom:solid '+this.borderColor+' 1px;font-size:1pt">&nbsp;'),
a+='<td style="width:'+this.aTab[b].width+";"+(this.aTab[b].visible?"":"display:none;")+'" '+("mouse"==this.event?"onmouseover":"onclick")+"=_select_tab(_tab_pages_["+this.tabPageId+"],"+b+") id=_tab_page_"+this.tabPageId+"_"+b+">"+(null==this.getTabHTML?this.aTab[b].getHTMLDefault():this.getTabHTML(this.aTab[b])),a+='<td width=4px style="border-bottom:solid '+this.borderColor+" 1px;font-size:1px;"+(this.aTab[b].visible?"":"display:none;")+'" id=_tab_page_'+this.tabPageId+"_"+b+"_2>&nbsp;";return a+=
"<td "+("right"==this.align?" width="+this.padding+" ":"")+' style="border-bottom:solid '+this.borderColor+' 1px">&nbsp;</table>'};this.selectTab=function(a){_select_tab(this,a)};this.setTabTitle=function(a,b){var c=document.getElementById("_tab_page_title_"+a);c&&null!=b&&(this.aTab[a].title=b,c.innerHTML=b)};this.getObject=function(){return document.getElementById("_tab_page_"+this.tabPageId)};this.getTabObject=function(a){return document.getElementById("_tab_page_"+this.tabPageId+"_"+a)};this.getTab=
function(a){return this.aTab[a]};this.onSelectTab=this.getTabHTML=null;this.borderColor="black"}
function Tab(a,b,c,d,e){this.title=b;this.status=d?d:0;this.visible=null==e?!0:e;if(0>=c&&null==c){c=0;b=this.title;for(d=0;d<b.length;d++)c=128<b.charCodeAt(d)?c+15:c+7}this.width=c;this.parent=a;this.tabIndex=a.aTab.length;this.getHTMLDefault=function(){var a="",a=1==this.status?"background:white;border-left:solid "+this.parent.borderColor+" 1px;border-top:solid "+this.parent.borderColor+" 1px;border-right:solid "+this.parent.borderColor+" 1px":"background:#e0e0e0;border-bottom:solid "+this.parent.borderColor+
" 1px";return'<div style="'+a+";width:"+this.width+";height:26px;padding-top:5px;text-align:center;cursor:"+(!$ap._IE()?"hand":"pointer")+';" onselectstart=false id=_tab_page_title_'+this.tabIndex+">"+this.title+"</div>"};this.setVisible=function(a){this.visible=null==a?!0:a;document.getElementById("_tab_page_"+this.parent.tabPageId+"_"+this.tabIndex)&&(document.getElementById("_tab_page_"+this.parent.tabPageId+"_"+this.tabIndex).style.display=this.visible?"":"none",document.getElementById("_tab_page_"+
this.parent.tabPageId+"_"+this.tabIndex+"_2").style.display=this.visible?"":"none")}}
function _select_tab(a,b){if(a.selectedIndex!=b){var c=a.selectedIndex;a.aTab[a.selectedIndex].status=0;var d=a.getTabObject(a.selectedIndex);null!=d&&(d.innerHTML=null==a.getTabHTML?a.aTab[a.selectedIndex].getHTMLDefault():a.getTabHTML(a.aTab[a.selectedIndex]));a.selectedIndex=b;a.aTab[a.selectedIndex].status=1;null!=d&&(d=a.getTabObject(a.selectedIndex),d.innerHTML=null==a.getTabHTML?a.aTab[a.selectedIndex].getHTMLDefault():a.getTabHTML(a.aTab[a.selectedIndex]));if(null!=a.onSelectTab&&null!=d)a.onSelectTab(b,
c)}};
