document.write("<style>a.treeview{color:black;text-decoration:none;cursor:default;}a.treeview:hover{color:black;text-decoration:none;}</style>");var _TREE_ID=0,_TVW_TEXTONLY=0,_TVW_TREELINE=1,_TVW_MULTISELECT=2,_TVW_ICON=4,_TVW_PLUSMINUS=8,_TVW_CHILD=0,_TVW_PREVIOUS=1,_TVW_NEXT=2,_TREE_ICON_DIR=$api._libaray_path+"/images/treeicon",_TREE_ICON_WIDTH=20,_TREE_ICON_HEIGHT=18,_TREE_NODE_TEXT_CLASS="";
function Tree(){this.tvwTextOnly=_TVW_TEXTONLY;this.tvwTreeLine=_TVW_TREELINE;this.tvwMultiSelect=_TVW_MULTISELECT;this.tvwIcon=_TVW_ICON;this.tvwPlusMinus=_TVW_PLUSMINUS;this.tvwChild=_TVW_CHILD;this.tvwPrevious=_TVW_PREVIOUS;this.tvwNext=_TVW_NEXT;this.id="_JS_TREE_"+_TREE_ID++;this.style=_TVW_TREELINE|_TVW_ICON;this.subNodes=[];this.lastNodeIndex=0;this.addNode=_addTreeNode;this.removeNode=_removeTreeNode;this.find=_getJSNode;this.getHTML=_getHtmlOfTreeView;this.getSelectedNode=_getSelectedTreeNode;
this.selectNode=_selectTreeNode2;this.getCheckedNodes=_getCheckedTreeNodes;this.handleEvent=_onTreeViewKeyEvent;this.enumerateNodes=_enumerateTreeNodes;this.expand=_expandAllTreeNodes;this.onChecked=""}
function TreeNode(a,b,c,d,e,f){this.id=null;this.icon1=a;this.icon2=b?b:a;this.text=c;this.script=d?d:"";this.key=null!=e?e:"";this.property=null!=f?f:"";this.subNodes=[];this.parTree=this.parNode=null;this.lastNodeIndex=0;this.addNode=_addTreeNode;this.removeNode=_removeTreeNode;this.find=_getJSNode;this.getText=_getTreeNodeText;this.setText=_setTreeNodeText;this.setIcon=_setTreeNodeIcon;this.expand=_expandTreeNode;this.focus=_setFocusOnTreeNode;this.moveUp=_moveTreeNodeUp;this.moveDown=_moveTreeNodeDown;
this.setSubNodes=_setSubTreeNodes;this.getPath=_getNodePathStr;this.setChecked=_setTreeNodeCheckedState;this.getChecked=_getTreeNodeCheckedState}function _addTreeNode(a,b,c){var d=null;if("string"==typeof a){if(d=this.find(a),!d)return}else d=a;null==b&&(b=_TVW_CHILD);switch(b){case _TVW_CHILD:return _add_childnode(this,d,c);case _TVW_PREVIOUS:return _insert_node_before(d,c,!1);case _TVW_NEXT:return _insert_node_before(d,c,!0)}}
function _add_childnode(a,b,c){null==b&&(b=a);b.id&&(c.id=b.id+"_"+b.lastNodeIndex++,c.key||(c.key=c.id));b.subNodes[b.subNodes.length]=c;null==b.parTree?(c.parNode=null,c.parTree=a):(c.parNode=b,c.parTree=b.parTree);_addSubNodeInDocument(c);c.parNode&&c.parTree&&_ifHasProperty(c.parTree.style,_TVW_MULTISELECT)&&b.getChecked()&&c.setChecked(!0);return c}
function _insert_node_before(a,b,c){if(!a)return null;for(var d=a.parNode?a.parNode:a.parTree,e=0,e=0;e<d.subNodes.length&&!(d.subNodes[e]==a);e++);if(c){for(f=d.subNodes.length;f>e+1;f--)d.subNodes[f]=d.subNodes[f-1];d.subNodes[e+1]=b}else{for(var f=d.subNodes.length;f>e;f--)d.subNodes[f]=d.subNodes[f-1];d.subNodes[e]=b}d.id&&(b.id=d.id+"_"+d.lastNodeIndex++,b.key||(b.key=b.id));b.parNode=a.parNode;b.parTree=a.parTree;_insertNodeInDocument(a,b,c);b.parNode&&b.parTree&&_ifHasProperty(b.parTree.style,
_TVW_MULTISELECT)&&b.parNode.getChecked()&&b.setChecked(!0);return b}
function _addSubNodeInDocument(a){if(null!=a.id){var b=document.getElementById(a.parTree.id);if(b){var c=a.parNode,d=null;null==c?(d=b.insertRow(),d.isRootNode=1==a.parTree.subNodes.length?"1":"0",d.id=a.id,_reset_nodehtml(a,!0,!0,!0),2<=a.parTree.subNodes.length&&_reset_nodehtml(a.parTree.subNodes[a.parTree.subNodes.length-2],!0,!1,!1,!0),2==a.parTree.subNodes.length&&(c=document.getElementById(a.parTree.subNodes[0].id),a=document.getElementById(a.parTree.subNodes[0].id+"_SubTree"),c.cells[0].style.display=
"",c.isRootNode="0",a&&(a.cells[0].style.display=""))):(b=document.getElementById(a.parNode.id+"_SubTree"))?(b=b.getElementsByTagName("TABLE")[0],d=b.insertRow(b.rows.length),d.id=a.id,_reset_nodehtml(a,!0,!0,!0),2<=c.subNodes.length&&_reset_nodehtml(c.subNodes[c.subNodes.length-2],!0,!1,!1,!0)):(b=document.getElementById(c.id),b.cells[0].innerHTML=_getNodeLineImg(c),b=_getTableFromTR(b).insertRow(b.rowIndex+1),b.id=c.id+"_SubTree",b.style.display="none",d=b.insertCell(b.cells.length),!_isLastNode(c)&&
_ifHasProperty(a.parTree.style,_TVW_TREELINE)&&!_ifHasProperty(a.parTree.style,_TVW_PLUSMINUS)&&(d.style.backgroundImage="url('"+_TREE_ICON_DIR+"/line.gif')"),b.insertCell(b.cells.length),d=b.insertCell(b.cells.length),d.innerHTML=_getSubNodesHtml(c),c==c.parTree.subNodes[0]&&1==c.parTree.subNodes.length&&(b.cells[0].style.display="none"))}}}
function _insertNodeInDocument(a,b,c){if(null!=b.id&&document.getElementById(b.parTree.id)){var d;d=null==b.parNode?document.getElementById(b.parTree.id):_getTableFromTR(document.getElementById(a.id));if(a){var e=document.getElementById(a.id).rowIndex;c&&(0<a.subNodes.length&&e++,e++);_reset_nodehtml(a,!0,!1,!1,!0);a=d.insertRow(e)}else a=d.insertRow();a.id=b.id;_reset_nodehtml(b,!0,!0,!0)}}
function _moveTreeNodeUp(){var a=this.parNode;a||(a=this.parTree);if(2>a.subNodes.length)return!1;for(var b=-1,c=0;c<a.subNodes.length;c++)if(a.subNodes[c]==this){b=c;break}if(0>=b)return!1;if(c=document.getElementById(this.parTree.id)){var c=c.SelectedItem,d=document.getElementById(this.id),e=document.getElementById(a.subNodes[b-1].id),f=_getTableFromTR(d),g=!1;0<this.subNodes.length&&(g="none"!=f.rows[d.rowIndex+1].style.display,f.deleteRow(d.rowIndex+1));f.deleteRow(d.rowIndex);d=f.insertRow(e.rowIndex);
d.id=this.id;d=this;a.subNodes[b]=a.subNodes[b-1];a.subNodes[b-1]=d;d.expand(!1);_reset_nodehtml(d,!0,!0,!0,!1);0<d.subNodes.length&&(f=f.insertRow(document.getElementById(d.id).rowIndex+1),f.id=d.id+"_SubTree",f.style.display="none",f.insertCell(f.cells.length).style.backgroundImage="url('"+_TREE_ICON_DIR+"/line.gif')",f.insertCell(f.cells.length),f.insertCell(f.cells.length).innerHTML=_getSubNodesHtml(d));a.subNodes[b].expand(!1);_reset_nodehtml(a.subNodes[b],!0,!1,!1,!0);c==d.id&&_select_treenode(c);
g&&_treenode_onexpand(d.id)}else a.subNodes[b]=a.subNodes[b-1],a.subNodes[b-1]=this;return!0}function _moveTreeNodeDown(){var a=this.parNode;a||(a=this.parTree);if(2>a.subNodes.length)return!1;for(var b=-1,c=0;c<a.subNodes.length;c++)if(a.subNodes[c]==this){b=c;break}return b>=a.subNodes.length-1?!1:a.subNodes[b+1].moveUp()}
function _setSubTreeNodes(a,b){if(0!=a.length){this.subNodes=null;this.subNodes=[];for(var c=0;c<a.length;c++){var d=new TreeNode(a[c].icon1,a[c].icon2,a[c].text,a[c].script,null,a[c].property);this.subNodes[this.subNodes.length]=d;d.id=this.id+"_"+this.lastNodeIndex++;a[c].id=d.id;a[c].key||(a[c].key=a[c].id);d.key=a[c].key!=a[c].id?a[c].key:d.id;d.parNode=this;d.parTree=this.parTree;0<a[c].subNodes.length&&d.setSubNodes(a[c].subNodes,!0)}if(!b){var c=document.getElementById(this.id),d=_getTableFromTR(c),
e=document.getElementById(this.id+"_SubTree");document.getElementById(this.id+"_SubTree")||(e=d.insertRow(c.rowIndex+1),e.id=this.id+"_SubTree",e.insertCell(e.cells.length),e.insertCell(e.cells.length),e.insertCell(e.cells.length),e.style.display="none");e.cells[2].innerHTML=_getSubNodesHtml(this);_reset_nodehtml(this,!0,!1,!1,!0)}}}
function _removeTreeNode(a){if(null==a)return!1;if("object"==typeof a&&a.parNode&&a.parNode!=this)return a.parNode.removeNode(a);for(var b=[],c=null,d=0;d<this.subNodes.length;d++){var e=!0;"object"==typeof a?a==this.subNodes[d]&&(e=!1,c=a):a==d&&(e=!1,c=this.subNodes[a]);e&&(b[b.length]=this.subNodes[d])}this.subNodes=b;c&&_removeNodeInDocument(this,c);return c}
function _removeNodeInDocument(a,b){var c=document.getElementById(b.parTree.id);if(c){var d=document.getElementById(b.id);c.SelectedItem==d.id&&c.removeAttribute("SelectedItem");c=_getTableFromTR(d);0<b.subNodes.length&&c.deleteRow(d.rowIndex+1);d.rowIndex==c.rows.length-1&&0<a.subNodes.length&&_reset_nodehtml(a.subNodes[a.subNodes.length-1],!0,!1,!1,!0);0==a.subNodes.length&&null!=a.parTree?(_reset_nodehtml(a,!0,!1,!1,!1),d=document.getElementById(a.id+"_SubTree"),_getTableFromTR(d).deleteRow(d.rowIndex)):
c.deleteRow(d.rowIndex)}}
function _reset_nodehtml(a,b,c,d,e){var f=document.getElementById(a.id);if(f){for(;3>f.cells.length;)f.insertCell(f.cells.length);f.setAttribute("ParentTree",a.parTree.id);f.setAttribute("key",a.key);f.setAttribute("ObjectType","TreeNode");_setObjectProperties(f,a.property);b&&(f.cells[0].innerHTML=_getNodeLineImg(a));c&&(_ifHasProperty(a.parTree.style,_TVW_MULTISELECT)?(f.cells[1].innerHTML=_getNodeChkBox(a),f.cells[1].style.width="14px"):f.cells[1].innerHTML="");d&&(f.cells[2].innerHTML=_getNodeHTML(a));
if(e&&0<a.subNodes.length&&(b=document.getElementById(a.id+"_SubTree")))b.cells[0].style.backgroundImage=!_isLastNode(a)&&_ifHasProperty(a.parTree.style,_TVW_TREELINE)?"url('"+_TREE_ICON_DIR+"/line.gif')":"";if(null==a.parNode&&1==a.parTree.subNodes.length&&(f.cells[0].style.display="none",b=document.getElementById(a.id+"_SubTree")))b.cells[0].style.display="none"}}
function _getJSNode(a,b){if(!b&&this.key==a||b&&this.id==a)return this;for(var c=this.subNodes.length-1;0<=c;c--){var d=this.subNodes[c].find(a,b);if(d)return d}return null}
function _getHtmlOfTreeView(){var a='<table id="'+this.id+'" onChecked="'+this.onChecked+'" cellpadding=0 cellspacing=0 border=0 style="cursor:default;font-size:9pt;" onselectstart="return false">';if(1==this.subNodes.length)a+='<tr isRootNode=1 ObjectType="TreeNode" id="'+this.subNodes[0].id+'" ParentTree="'+this.subNodes[0].parTree.id+'" key="'+this.subNodes[0].key+'" '+this.subNodes[0].property+"><td>"+(_ifHasProperty(this.style,_TVW_MULTISELECT)?"<td><div style=width:14>"+_getNodeChkBox(this.subNodes[0])+
"</div>":"<td>")+"<td>"+_getNodeHTML(this.subNodes[0]),a+='<tr id="'+this.subNodes[0].id+'_SubTree"><td><td><td>',a+=_getSubNodesHtml(this.subNodes[0]);else for(var b=0;b<this.subNodes.length;b++)a+=_getTreeNodeHtml(this.subNodes[b],!0);return a+"</table>"}
function _getTreeNodeHtml(a,b){var c="",c='<tr id="'+a.id+'" ObjectType="TreeNode" ParentTree="'+a.parTree.id+'" key="'+a.key+'" '+a.property+" >",c=c+("<td width="+_TREE_ICON_WIDTH+">"+_getNodeLineImg(a)),c=_ifHasProperty(a.parTree.style,_TVW_MULTISELECT)?c+("<td><div style=width:14>"+_getNodeChkBox(a)+"</div>"):c+"<td>",c=c+("<td>"+_getNodeHTML(a));b&&0<a.subNodes.length&&(c+='<tr id="'+a.id+'_SubTree" style="display:none;"><td style="'+(!_isLastNode(a)&&_ifHasProperty(a.parTree.style,_TVW_TREELINE)&&
!_ifHasProperty(a.parTree.style,_TVW_PLUSMINUS)?"background:url('"+_TREE_ICON_DIR+"/line.gif')":"")+'">&nbsp;<td><td padding-bottom:8px>',c+=_getSubNodesHtml(a));return c}function _getSubNodesHtml(a){for(var b='<table cellpadding=0 cellspacing=0 border=0 style="cursor:default;font-size:9pt;" >',c=0;c<a.subNodes.length;c++)b+=_getTreeNodeHtml(a.subNodes[c],!0);return b+"</table>"}
function _isLastNode(a){var b=!1;return b=null==a.parNode?a==a.parTree.subNodes[a.parTree.subNodes.length-1]:a==a.parNode.subNodes[a.parNode.subNodes.length-1]}
function _getNodeLineImg(a){var b=a.parTree;if(_ifHasProperty(a.parTree.style,_TVW_PLUSMINUS))return 0==a.subNodes.length?"<span style=width:20px;>&nbsp;</span>":'<span style="width:20px;"><img id="'+a.id+'_lineicon1" src='+_TREE_ICON_DIR+'/plus.gif align=absmiddle width=9 height=9 style="display:'+(b.expanOnInit?"none":"")+'" onclick="_treenode_onexpand(\''+a.id+'\')"><img id="'+a.id+'_lineicon2" src='+_TREE_ICON_DIR+'/minus.gif align=absmiddle width=9 height=9 style="display:'+(b.expanOnInit?"":
"none")+';" onclick="_treenode_onexpand(\''+a.id+"')\"></span>";if(_ifHasProperty(a.parTree.style,_TVW_TREELINE)){var c="",d=_isLastNode(a);return c=0==a.subNodes.length?d?c+("<img src="+_TREE_ICON_DIR+"/cornerline.gif align=absmiddle width="+_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+">"):c+("<img src="+_TREE_ICON_DIR+"/crossline.gif align=absmiddle width="+_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+">"):d?c+('<img id="'+a.id+'_lineicon1" src='+_TREE_ICON_DIR+"/cornerplusnode.gif align=absmiddle width="+
_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+' style="display:'+(b.expanOnInit?"none":"")+'" onclick="_treenode_onexpand(\''+a.id+'\')"><img id="'+a.id+'_lineicon2" src='+_TREE_ICON_DIR+"/cornerminusnode.gif align=absmiddle width="+_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+' style="display:'+(b.expanOnInit?"":"none")+';" onclick="_treenode_onexpand(\''+a.id+"')\">"):c+('<img id="'+a.id+'_lineicon1" src='+_TREE_ICON_DIR+"/plusnode.gif align=absmiddle width="+_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+
' style="display:'+(b.expanOnInit?"none":"")+'" onclick="_treenode_onexpand(\''+a.id+'\')"><img id="'+a.id+'_lineicon2" src='+_TREE_ICON_DIR+"/minusnode.gif align=absmiddle width="+_TREE_ICON_WIDTH+" height="+_TREE_ICON_HEIGHT+' style="display:'+(b.expanOnInit?"":"none")+';" onclick="_treenode_onexpand(\''+a.id+"')\">")}return null==a.parNode?"&nbsp;":"<span style=width:20px;>&nbsp</span>"}
function _getNodeChkBox(a){return'<div style="font-size:9pt;border:solid black 1px;width:12px;height:12px;overflow:hidden;cursor:default;background:white;" id="chk'+a.id+'" onclick="_node_onSelectCheckbox(\''+a.id+"')\">&nbsp;</div>"}
function _getNodeHTML(a){var b="<nobr>";_ifHasProperty(a.parTree.style,_TVW_ICON)&&(b=-1!=a.icon1.indexOf(".gif")||-1!=a.icon1.indexOf(".jpg")?b+('<img src="'+a.icon1+'" align=absmiddle width=16 height=16 id="'+a.id+'_icon1"><img src="'+a.icon2+'" style="display:none;" align=absmiddle width=16 height=16 id="'+a.id+'_icon2"><font style="font-size:3px;">&nbsp;</font>'):b+('<span id="'+a.id+'_icon1" class="'+a.icon1+'"></span><span id="'+a.id+'_icon2" class="'+a.icon2+'" style="display:none;"></span><font style="font-size:3px;">&nbsp;</font>'));
return b+="<a "+(-1!=window.navigator.appVersion.indexOf("MSIE 5")&&window==top?"":"href=#TNA")+' id="'+a.id+"_text\" onmousedown=_select_treenode('"+a.id+"') style=\"height:16px;padding-top:2px;padding-left:3px;padding-right:3px;\" ondblclick=_treenode_onexpand('"+a.id+"') onclick=\""+(a.script?a.script:"")+'" class=treeview>'+(""==_TREE_NODE_TEXT_CLASS?"":"<font class="+_TREE_NODE_TEXT_CLASS+">")+a.text.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\[TAG:/g,"<").replace(/:TAG\]/g,">")+(""==
_TREE_NODE_TEXT_CLASS?"":"</font>")+"</a></nobr>"}function _ifHasProperty(a,b){return(a&b)==b}
function _select_treenode(a){var b=document.getElementById(a);if(b){var c=document.getElementById(b.getAttribute("ParentTree"));_disselectTreeNode(c.id);c.SelectedItem=b.id;if(b=document.getElementById(b.id+"_text")){b.style.backgroundColor="darkblue";b.style.color="white";try{b.focus()}catch(d){}}b=document.getElementById(a+"_icon1");a=document.getElementById(a+"_icon2");b&&a&&(b.style.display="none",a.style.display="")}}
function _disselectTreeNode(a){a=document.getElementById(a);if(a.SelectedItem){var b=document.getElementById(a.SelectedItem);if(!b)return;var c=document.getElementById(b.id+"_text");c&&(c.style.backgroundColor="",c.style.color="");null==document.getElementById(b.id+"_SubTree")&&(c=document.getElementById(b.id+"_icon1"),b=document.getElementById(b.id+"_icon2"),c&&b&&(c.style.display="",b.style.display="none"))}a.removeAttribute("SelectedItem")}
function _expandTreeNode(a){null==a&&(a=!0);_treenode_onexpand(this.id,a)}
function _treenode_onexpand(a,b){var c=document.getElementById(a),d=document.getElementById(a+"_SubTree");null!=d&&(null==b&&(b="none"==d.style.display),"1"==c.isRootNode&&(b=!0),d.style.display=b?"":"none",c=document.getElementById(a+"_icon1"),d=document.getElementById(a+"_icon2"),c&&d&&(c.style.display=b?"none":"",d.style.display=b?"":"none"),c=document.getElementById(a+"_lineicon1"),d=document.getElementById(a+"_lineicon2"),c&&d&&(c.style.display=b?"none":"",d.style.display=b?"":"none"))}
function _setFocusOnTreeNode(){for(var a=this;null!=a;a=a.parNode)a.expand();_select_treenode(this.id)}function _getSelectedTreeNode(){var a=document.getElementById(this.id).SelectedItem;if(a)return document.getElementById(a)}function _selectTreeNode2(a){if("string"==typeof a&&(a=this.find(a),null==a))return;_select_treenode(a.id);a.expand()}function _getTreeNodeText(){return this.text.replace(/\[TAG:.*:TAG\]/g,"")}
function _setTreeNodeText(a){this.text=a;document.getElementById(this.id)&&(document.getElementById(this.id+"_text").innerHTML=$api.fn.htmlEncode(a).replace(/\[TAG:/g,"<").replace(/:TAG\]/g,">"))}
function _setTreeNodeIcon(a,b){if(null==b||""==b)b=a;this.icon1=a;this.icon2=b;-1!=a.indexOf(".gif")||-1!=a.indexOf(".jpg")?(document.getElementById(this.id+"_icon1").src=a,document.getElementById(this.id+"_icon2").src=b):(document.getElementById(this.id+"_icon1").className=a,document.getElementById(this.id+"_icon2").className=b)}
function _node_onSelectCheckbox(a){_setSingleNodeChecked(a);var b=document.getElementById(a).getAttribute("isChecked");_setSubNodesChecked(a,b);_setParNodeChecked(a);var c=document.getElementById(a).getAttribute("ParentTree");""!=document.getElementById(c).getAttribute("onChecked")&&eval(document.getElementById(c).getAttribute("onChecked")+"('"+a+"',"+b+");")}
function _setSingleNodeChecked(a,b){var c=document.getElementById("chk"+a),d=document.getElementById(a);d&&c&&(null==b&&(b="1"==d.getAttribute("isChecked")?"0":"1"),"0"!=b?(c.innerHTML='<div style="margin-top:-1px;margin-left:-1px;"><b>\u221a</b></div>',c.style.backgroundColor="2"==b?"#E0E0E0":"white"):(c.style.backgroundColor="white",c.innerHTML="&nbsp;"),d.setAttribute("isChecked",b))}
function _setSubNodesChecked(a,b){for(var c=0;;){var d=a+"_"+c;if(document.getElementById("chk"+d))_setSingleNodeChecked(d,b),_setSubNodesChecked(d,b);else break;c++}}
function _setParNodeChecked(a){if(-1!=a.indexOf("_")){var a=a.substring(0,a.lastIndexOf("_")),b=document.getElementById(a);if(""!=a&&b){for(var c=b=0,d=null;;){var e=document.getElementById(a+"_"+b);if(!e)break;e=e.getAttribute("isChecked");null==e&&(e="0");"1"==e&&c++;if("2"==e){d="2";break}b++}"2"!=d&&(d=0==c?"0":c==b?"1":"2");_setSingleNodeChecked(a,d);_setParNodeChecked(a)}}}
function _setTreeNodeCheckedState(a){a!=("1"==document.getElementById(this.id).getAttribute("isChecked"))&&_node_onSelectCheckbox(this.id)}function _getCheckedTreeNodes(a,b){null==b&&(b=this);var c=document.getElementById(b.id),d="";if(!c)return"";if("1"==c.getAttribute("isChecked")&&(!a||0==b.subNodes.length))return c.id;for(c=0;c<b.subNodes.length;c++){var e=_getCheckedTreeNodes(a,b.subNodes[c]);0<e.length&&0<d.length&&(d+="\n");d+=e}return d}
function _getTreeNodeCheckedState(){var a=document.getElementById(this.id);return null==a?!1:"1"==a.getAttribute("isChecked")}
function _onTreeViewKeyEvent(a){var b=this.getSelectedNode();switch(a.keyCode){case 13:try{null!=b&&(_treenode_onexpand(b.id),document.getElementById(b.id+"_text").onclick())}catch(c){}return!0;case 38:return b=null==b?document.getElementById(this.subNodes[0].id):_getNextTreeNode(b,-1,document.getElementById(this.id)),_select_treenode(b.id),!0;case 40:return b=null==b?document.getElementById(this.subNodes[0].id):_getNextTreeNode(b,1,document.getElementById(this.id)),_select_treenode(b.id),!0;case 27:_disselectTreeNode(this.id)}return!1}
function _getNextTreeNode(a,b,c){for(var d=a.sourceIndex,e=null;;){d+=b;d<=c.sourceIndex?d=c.sourceIndex+c.all.length:d>=c.sourceIndex+c.all.length&&(d=c.sourceIndex);if(d==a.sourceIndex)return a;e=document.all(d);if("TR"==e.tagName){for(var f=e;f!=c&&!("none"==f.style.display);)f=f.parentElement;if(f==c&&e.ParentTree&&""==e.style.display)return e}}}function _setTreeIconDir(a){"/"==a.substring(a.length-1)&&(a=a.substring(0,a.length-1));_TREE_ICON_DIR=a}
function _setObjectProperties(a,b){if(0!=b.length){for(var c=0,d=[],e="";c<b.length;){var f=b.charAt(c);if("="==f||" "==f)""!=e&&(d[d.length]=e),"="==f&&(d[d.length]="="),e="";else if(('"'==f||"'"==f)&&""==e)for(var g=c+1;g<b.length;){var h=b.charAt(g);if(h!=f)e+=h;else{c=g;d[d.length]=e;e="";break}g++}else e+=f;c++}""!=e&&(d[d.length]=e);for(c=0;c<d.length;){for(;"="!=d[c+1]&&c<d.length-2;)c++;if(c>d.length-3)break;a.setAttribute(d[c],d[c+2]);c+=3}}}
function _expandAllTreeNodes(a){if(1==this.subNodes.length)for(var b=0;b<this.subNodes[0].subNodes.length;b++)this.subNodes[0].subNodes[b].expand(a);else for(b=0;b<this.subNodes.length;b++)this.subNodes[b].expand(a)}function _getTableFromTR(a){for(;a&&"TABLE"!=a.tagName;)a=a.parentNode;return a}function _enumerateTreeNodes(){for(var a=_enumerateSubNodes(this).split("\n"),b=[],c=0;c<a.length;c++)b[b.length]=document.getElementById(a[c]);return b}
function _enumerateSubNodes(a){var b="";null!=a.parTree&&(b=a.id);for(var c=0;c<a.subNodes.length;c++)b+=(0<b.length?"\n":"")+_enumerateSubNodes(a.subNodes[c]);return b}function _getNodePathStr(){for(var a="",b=this;b;)a="/"+b.text+a,b=b.parNode;return a};
